### ISSUE TITLE
salt-ssh tests sometimes fail on fedora 27

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1047]
sometimes all of the ssh tests fail on fedora 27

integration.ssh.test_master.SSHMasterTestCase.test_can_it_ping
integration.ssh.test_master.SSHMasterTestCase.test_grains_items
integration.ssh.test_master.SSHMasterTestCase.test_service
integration.ssh.test_master.SSHMasterTestCase.test_state_apply
integration.ssh.test_master.SSHMasterTestCase.test_state_highstate
integration.ssh.test_state.SSHStateTest.test_show_highstate
integration.ssh.test_state.SSHStateTest.test_show_lowstate
integration.ssh.test_state.SSHStateTest.test_state_apply
integration.ssh.test_state.SSHStateTest.test_state_high
integration.ssh.test_state.SSHStateTest.test_state_low
integration.ssh.test_state.SSHStateTest.test_state_request_check_clear
integration.ssh.test_state.SSHStateTest.test_state_run_request
integration.ssh.test_state.SSHStateTest.test_state_show_sls
integration.ssh.test_state.SSHStateTest.test_state_show_top
integration.ssh.test_state.SSHStateTest.test_state_single
integration.ssh.test_state.SSHStateTest.test_state_sls_id
integration.ssh.test_state.SSHStateTest.test_state_sls_wrong_id
integration.ssh.test_state.SSHStateTest.test_show_highstate
integration.ssh.test_state.SSHStateTest.test_show_lowstate
integration.ssh.test_state.SSHStateTest.test_state_apply
integration.ssh.test_state.SSHStateTest.test_state_high
integration.ssh.test_state.SSHStateTest.test_state_low
integration.ssh.test_state.SSHStateTest.test_state_request_check_clear
integration.ssh.test_state.SSHStateTest.test_state_run_request
integration.ssh.test_state.SSHStateTest.test_state_running
integration.ssh.test_state.SSHStateTest.test_state_show_sls
integration.ssh.test_state.SSHStateTest.test_state_show_top
integration.ssh.test_state.SSHStateTest.test_state_single
integration.ssh.test_state.SSHStateTest.test_state_sls_id
integration.ssh.test_state.SSHStateTest.test_state_sls_wrong_id

here is one failure:

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/ssh/test_master.py", line 24, in test_can_it_ping
    self.assertEqual(ret, True)
AssertionError: False != True
```

and 

```
 File "<string>", line 203, in <module>\n  File "<string>", line 337, in <module>\n  File "<string>", line 228, in main\n  File "<string>", line 180, in unpack_thin\n  File "/usr/lib64/python2.7/tarfile.py", line 2075, in extractall\n    for tarinfo in members:\n  File "/usr/lib64/python2.7/tarfile.py", line 2510, in next\n    tarinfo = self.tarfile.next()\n  File "/usr/lib64/python2.7/tarfile.py", line 2358, in next\n    tarinfo = self.tarinfo.fromtarfile(self)\n  File "/usr/lib64/python2.7/tarfile.py", line 1251, in fromtarfile\n    buf = tarfile.fileobj.read(BLOCKSIZE)\n  File "/usr/lib64/python2.7/gzip.py", line 268, in read\n    self._read(readsize)\n  File "/usr/lib64/python2.7/gzip.py", line 303, in _read\n    self._read_gzip_header()\n  File "/usr/lib64/python2.7/gzip.py", line 197, in _read_gzip_header\n    raise IOError, \'Not a gzipped file\'\nIOError: Not a gzipped file\n', u'_error': u'Failed to return clean data'} is not an instance of (<type 'basestring'>,)
```

for this test: integration.ssh.test_state.SSHStateTest.test_state_show_sls

2018.3 and develop

PY2

**Comment by rallytime** [comment]
We have done some work recently in this area. I haven't seen these fail recently except when other ssh tests are failing. I think we might be good to close this one. I'll keep my eye out for a bit before closing.
