### ISSUE TITLE
[2018.3.3] integration.states.test_git.GitTest.test_cloned_with_nonexistant_branch failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1068]
`integration.states.test_git.GitTest.test_cloned_with_nonexistant_branch` test is failing on cent6 python2 

https://jenkinsci.saltstack.com/job/2018.3.3/job/salt-centos-6-py2/2/

Here is the error:

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 1037, in <lambda>
    lambda testcase, *args, **kwargs: self.wrap(testcase, *args, **kwargs)  # pylint: disable=W0108
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 1045, in wrap
    return self.func(testcase, tempdir, *args, **kwargs)
  File "/tmp/kitchen/testing/tests/integration/states/test_git.py", line 658, in test_cloned_with_nonexistant_branch
    assert ret['result'] is False
AssertionError
```

**Comment by Ch3LL** [comment]
okay i found out why this test is failing only on cent6. It is because the git versions differ and on older git versions it returns an exit code of 0 when branch does not exist.

To show this point further.

on cent6:

```
[root@ip-10-0-0-144 ~]# git clone --branch thisbranchdoesnotexist -- https://github.com/saltstack/salt-test-repo.git /tmp/test
Initialized empty Git repository in /tmp/test/.git/
remote: Counting objects: 13, done.
Unpacking objects: 100% (13/13), done.
remote: Total 13 (delta 0), reused 0 (delta 0), pack-reused 13
warning: Remote branch thisbranchdoesnotexist not found in upstream origin, using HEAD instead
[root@ip-10-0-0-144 ~]# echo $?
0
[root@ip-10-0-0-144 ~]# git --version
git version 1.7.1
```


arch:

```
➜  ~ git clone --branch thisbranchdoesnotexist -- https://github.com/saltstack/salt-test-repo.git /tmp/test
Cloning into '/tmp/test'...
fatal: Remote branch thisbranchdoesnotexist not found in upstream origin
➜  ~ echo $?
128
➜  ~ git --version
git version 2.15.1
```

**Comment by Ch3LL** [comment]
okay i found out its this commit: https://github.com/git/git/commit/920b691 that changed it from a warning to calling `die` and returning exit code 128.

This first appeared in git version v1.7.10

**Comment by Ch3LL** [comment]
ping @terminalmage i've been glancing at this one and i'm not certain where the right fix would be here. Should we just require git >1.7.10 to use the clone state or should we be be catching the stderr here: https://github.com/saltstack/salt/blob/develop/salt/modules/git.py#L388 and then raise a CommandExecutionError message.

**Comment by Ch3LL** [comment]
i think i might take the approach to check if the branch exists before checking out on versions <=1.7.10. i'll see if thats possible.

**Comment by Ch3LL** [comment]
okay i have this so far:

```
diff --git a/salt/modules/git.py b/salt/modules/git.py
index 269c3f1cb2..9d11d06f4b 100644
--- a/salt/modules/git.py
+++ b/salt/modules/git.py
@@ -1045,9 +1045,10 @@ def clone(cwd,
     except ValueError as exc:
         raise SaltInvocationError(exc.__str__())
 
+    opts = _format_opts(opts)
     command = ['git'] + _format_git_opts(git_opts)
     command.append('clone')
-    command.extend(_format_opts(opts))
+    command.extend(opts)
     command.extend(['--', url])
     if name is not None:
         command.append(name)
@@ -1063,6 +1064,12 @@ def clone(cwd,
         # On Windows, just fall back to None (runs git clone command using the
         # home directory as the cwd).
         clone_cwd = '/tmp' if not salt.utils.platform.is_windows() else None
+    if '--branch' in opts and _LooseVersion(version(versioninfo=False)) <= _LooseVersion('1.7.10'):
+        branch = opts[opts.index('--branch') +1]
+        if not ls_remote(cwd, remote=url, ref=branch):
+            raise CommandExecutionError('Branch {0} does not exist. Exiting'
+                                        ' attempt to clone'.format(branch))
+
     _git_run(command,
              cwd=clone_cwd,
              user=user,
```

just need to test this tomorrow.

**Comment by terminalmage** [comment]
I would just skip the test on git > 1.7.10. There are very few non-EOL LTS releases which have that old of a git release, and this test is specifically designed to test the behavior present in newer git versions anyway.

**Comment by terminalmage** [comment]
Ahh good, I see you properly interpreted my typo :smile: Sorry, I should have said `git < 1.7.10`.
