### ISSUE TITLE
[2018.3.3] Fedora 28 not running tests

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1077]
https://jenkinsci.saltstack.com/job/2018.3.3/view/Python3/job/salt-fedora-28-py3/6/consoleFull

```
03:14:06        Traceback (most recent call last):
03:14:06          File "/tmp/kitchen/testing/tests/runtests.py", line 875, in <module>
03:14:06            main()
03:14:06          File "/tmp/kitchen/testing/tests/runtests.py", line 858, in main
03:14:06            status = parser.run_integration_tests()
03:14:06          File "/tmp/kitchen/testing/tests/runtests.py", line 764, in run_integration_tests
03:14:06            status.append(self.run_integration_suite(**TEST_SUITES[suite]))
03:14:06          File "/tmp/kitchen/testing/tests/runtests.py", line 572, in run_integration_suite
03:14:06            return self.run_suite(full_path, display_name, suffix='test_*.py')
03:14:06          File "/tmp/kitchen/testing/tests/support/parser/__init__.py", line 490, in run_suite
03:14:06            tests = loader.discover(path, suffix, self.testsuite_directory)
03:14:06          File "/usr/lib64/python3.6/unittest/loader.py", line 341, in discover
03:14:06            tests = list(self._find_tests(start_dir, pattern))
03:14:06          File "/usr/lib64/python3.6/unittest/loader.py", line 398, in _find_tests
03:14:06            full_path, pattern, namespace)
03:14:06          File "/usr/lib64/python3.6/unittest/loader.py", line 452, in _find_test_path
03:14:06            return self.loadTestsFromModule(module, pattern=pattern), False
03:14:06          File "/usr/lib64/python3.6/unittest/loader.py", line 123, in loadTestsFromModule
03:14:06            tests.append(self.loadTestsFromTestCase(obj))
03:14:06          File "/usr/lib64/python3.6/unittest/loader.py", line 92, in loadTestsFromTestCase
03:14:06            loaded_suite = self.suiteClass(map(testCaseClass, testCaseNames))
03:14:06          File "/usr/lib64/python3.6/unittest/suite.py", line 24, in __init__
03:14:06            self.addTests(tests)
03:14:06          File "/usr/lib64/python3.6/unittest/suite.py", line 57, in addTests
03:14:06            for test in tests:
03:14:06          File "/tmp/kitchen/testing/tests/integration/modules/test_shadow.py", line 34, in __init__
03:14:06            self._password = self.run_function('shadow.gen_password', ['Password1234'])
03:14:06          File "/tmp/kitchen/testing/tests/support/case.py", line 812, in run_function
03:14:06            function, minion_tgt, orig
03:14:06          File "/usr/lib64/python3.6/unittest/case.py", line 683, in skipTest
03:14:06            raise SkipTest(reason)
03:14:06        unittest.case.SkipTest: WARNING(SHOULD NOT HAPPEN #1935): Failed to get 'shadow.gen_password' from the minion 'minion'. Command output: {'minion': None}
03:14:06        Copying /tmp/xml-unittests-output to artifacts/
03:14:07        chmod: cannot access '/tmp/coverage.xml': No such file or directory
```

This is right after the test runner starts, so we aren't getting test results for this OS currently.

**Comment by Ch3LL** [comment]
i'll take a look at this after the cloud tests

**Comment by Ch3LL** [comment]
still failing looking into it

**Comment by gtmanfred** [comment]
Coverage has nothing to do with why this is failing, the chmod cannot access coverage.xml is when it tries to copy the files back, the error is that it never ran any of the tests.

**Comment by Ch3LL** [comment]
tests are running now woot! https://jenkinsci.saltstack.com/job/2018.3.3/view/Python3/job/salt-fedora-28-py3/11/console
