### ISSUE TITLE
[2017.7] test_check_request test is failing on Debian 9

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#1120]
The following test is failing on the Debian 9 Python 2 builds on the 2017.7 branch:

- unit.modules.test_state.StateTestCase.test_check_request 

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/modules/test_state.py", line 808, in test_check_request
    with patch('salt.utils.fopen', mock_open()):
  File "/usr/local/lib/python2.7/dist-packages/coverage/control.py", line 296, in _should_trace
    canonical, reason = self._should_trace_with_reason(filename, frame)
  File "/usr/local/lib/python2.7/dist-packages/coverage/control.py", line 261, in _should_trace_with_reason
    canonical = self.file_locator.canonical_filename(filename)
  File "/usr/local/lib/python2.7/dist-packages/coverage/files.py", line 46, in canonical_filename
    cf = abs_file(filename)
  File "/usr/local/lib/python2.7/dist-packages/coverage/files.py", line 118, in abs_file
    path = os.path.abspath(os.path.realpath(path))
  File "/usr/lib/python2.7/posixpath.py", line 375, in realpath
    path, ok = _joinrealpath('', filename, {})
  File "/usr/lib/python2.7/posixpath.py", line 400, in _joinrealpath
    if not islink(newpath):
  File "/usr/lib/python2.7/posixpath.py", line 135, in islink
    st = os.lstat(path)
TypeError: coercing to Unicode: need string or buffer, bool found
```

https://jenkinsci.saltstack.com/job/2017.7/job/salt-debian-9-py2/lastCompletedBuild/testReport/

The test is fine in the 2018.3 branch, so something is off in the 2017.7 branch specifically.

@garethgreenaway Can you take a look here when you get a moment?

**Comment by rallytime** [comment]
Fixed yay! Thanks @garethgreenaway
