### ISSUE TITLE
[2017.7] opensuse not bootstrapping

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1270]
opensuse tests on 2017.7 are not bootstrapping:

```
02:45:34                  ID: setuptools
02:45:34            Function: pip.installed
02:45:34                Name: setuptools>=30
02:45:35              Result: False
02:45:35             Comment: An exception occurred in this state: Traceback (most recent call last):
02:45:35                 File "/usr/lib/python2.7/site-packages/salt/state.py", line 1889, in call
02:45:35                   **cdata['kwargs'])
02:45:35                 File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1839, in wrapper
02:45:35                   return f(*args, **kwargs)
02:45:35                 File "/tmp/kitchen/var/cache/salt/minion/extmods/states/pip_state.py", line 57, in installed
02:45:35                   return pip_state_installed(name, **kwargs)
02:45:35                 File "/usr/lib/python2.7/site-packages/salt/states/pip_state.py", line 911, in installed
02:45:35                   if pkg_name.lower() in already_installed_packages:
02:45:35               AttributeError: 'NoneType' object has no attribute 'lower'
02:45:35             Started: 07:41:30.866274
02:45:35            Duration: 2083.171 ms
```

https://jenkinsci.saltstack.com/job/2017.7/view/Python3/job/salt-opensuse-py3/33/consoleFull

**Comment by garethgreenaway** [comment]
@Ch3LL This seems like it might fix this particular issue.  https://github.com/saltstack/salt/pull/50963

**Comment by Ch3LL** [comment]
bootstrapping now :)
