### ISSUE TITLE
[2018.3.4] centos 7 tests timing out

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#1273]
the centos7 python2 tests are timing out. in the logs I'm seeing a lot of these failures:

```
:787 ][CRITICAL] Failed to load grains defined in grain file custom_grains.test in function <function test at 0x7f42daeed5f0>, error:
04:18:20        Traceback (most recent call last):
04:18:20          File "/tmp/kitchen/testing/salt/loader.py", line 778, in grains
04:18:20            ret = funcs[key](proxy)
04:18:20          File "/tmp/salt-tests-tmpdir/rootdir/var/cache/salt/minion/extmods/grains/custom_grains.py", line 5, in test
04:18:20            return {'custom_grain_test': 'itworked' if 'os' in grains else 'itdidntwork'}
04:18:20        TypeError: argument of type 'NoneType' is not iterable
```

https://jenkinsci.saltstack.com/job/2018.3.4/job/salt-centos-7-py2/9/console

**Comment by terminalmage** [comment]
Fixed in #51445.

**Comment by frogunder** [comment]
This can be closed. I do not see this failure/error on the cent7 test anymore.
