### ISSUE TITLE
Fix CentOS 6 jenkins runs

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#316]
@rallytime commented on [Fri Apr 28 2017](https://github.com/saltstack/zh/issues/1281)

The VM is now getting bootstrapped and is running a couple of states, but after getting the external IP, we fail the ssh command:
```
18:05:52  * Running command: salt -t 100 -l info Zjk-2017_5-lin-cent6-36 saltutil.sync_all
18:05:52 --------------------------------------------------------------------------------
18:05:59 Zjk-2017_5-lin-cent6-36:
18:05:59     ----------
18:05:59     beacons:
18:05:59     engines:
18:05:59     grains:
18:05:59         - grains.external_ip
18:05:59         - grains.python_executable
18:05:59     log_handlers:
18:05:59     modules:
18:05:59         - modules.pip
18:05:59         - modules.runtests
18:05:59         - modules.six
18:05:59     output:
18:05:59     proxymodules:
18:05:59     renderers:
18:05:59     returners:
18:05:59     sdb:
18:05:59     states:
18:05:59         - states.pip2_state
18:05:59         - states.pip3_state
18:05:59         - states.pip_state
18:05:59         - states.runtests
18:05:59     utils:
18:06:00 --------------------------------------------------------------------------------
18:06:00  * Command execution succeeded. Exit code: 0
18:06:00 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
18:06:00  * Fetching the IP address of the minion. Attempt 1/3
18:06:00 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
18:06:00  * Running command: salt --out=json -l info Zjk-2017_5-lin-cent6-36 grains.get external_ip
18:06:00 --------------------------------------------------------------------------------
18:06:02 --------------------------------------------------------------------------------
18:06:02  * Command execution succeeded. Exit code: 0
18:06:02 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
18:06:03 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
18:06:03  * Running command: ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -oIdentityFile=/var/jenkins/workspace/branch_tests/2017.5/salt-linode-cent6/jenkins_test_account_key root@4 'echo "root login possible"'
18:06:03 --------------------------------------------------------------------------------
18:06:03 ssh: connect to host 4 port 22: Invalid argument
18:06:04 --------------------------------------------------------------------------------
18:06:04  * Failed execute command. Exit code: 255
```

---

@rallytime commented on [Mon May 01 2017](https://github.com/saltstack/zh/issues/1281#issuecomment-298437711)

This was a bug in salt-testing. The released version of salt-testing has a ton of refactors in the jenkins.py file, which caused a regression in getting the minion's ip address.

This has been fixed in salt-testing upstream with https://github.com/saltstack/salt-testing/commit/22a0dd6d18baa3d76711978b76d76c78ab249f9f

I have patched the jenkins.py file until another release of salttesting is available.

---

@rallytime commented on [Mon May 01 2017](https://github.com/saltstack/zh/issues/1281#issuecomment-298437918)

Now that the salt-jenkins states are installing, we have a new failure on the CentOS 6 build:
```
21:24:58  * Running SSH command: ['ssh', '-oStrictHostKeyChecking=no', '-oUserKnownHostsFile=/dev/null', '-oControlPath=none', '-oPasswordAuthentication=no', '-oChallengeResponseAuthentication=no', '-oPubkeyAuthentication=yes', '-oKbdInteractiveAuthentication=no', '-oIdentityFile=/var/jenkins/workspace/branch_tests/2017.5/salt-linode-cent6/jenkins_test_account_key', '-t', '-t', 'root@50.116.9.92', u"'/usr/bin/python2.7 //testing/tests/runtests.py -v --run-destructive --sysinfo --transport=zeromq --output-columns=80 --ssh --coverage-xml=/tmp/coverage.xml --xml=/tmp/xml-unittests-output'"]
21:24:58 >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
21:24:58  * Running command: ssh -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null -oControlPath=none -oPasswordAuthentication=no -oChallengeResponseAuthentication=no -oPubkeyAuthentication=yes -oKbdInteractiveAuthentication=no -oIdentityFile=/var/jenkins/workspace/branch_tests/2017.5/salt-linode-cent6/jenkins_test_account_key -t -t root@50.116.9.92 '/usr/bin/python2.7 //testing/tests/runtests.py -v --run-destructive --sysinfo --transport=zeromq --output-columns=80 --ssh --coverage-xml=/tmp/coverage.xml --xml=/tmp/xml-unittests-output'
21:24:58 --------------------------------------------------------------------------------
21:24:58 Warning: Permanently added '50.116.9.92' (RSA) to the list of known hosts.
21:24:59 Connection to 50.116.9.92 closed.
21:24:59 Traceback (most recent call last):
21:24:59   File "//testing/tests/runtests.py", line 59, in <module>
21:24:59     from tests.integration import TestDaemon  # pylint: disable=W0403
21:24:59   File "//testing/tests/integration/__init__.py", line 35, in <module>
21:24:59     from tests.support.processes import *  # pylint: disable=wildcard-import
21:24:59   File "//testing/tests/support/processes.py", line 18, in <module>
21:24:59     from pytestsalt.utils import SaltRunEventListener as PytestSaltRunEventListener
21:24:59 ImportError: No module named pytestsalt.utils
21:25:00 --------------------------------------------------------------------------------
21:25:00  * Failed execute command. Exit code: 1
21:25:00 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
21:25:00  * The execution of the test command [u'/usr/bin/python2.7', '//testing/tests/runtests.py', '-v', '--run-destructive', '--sysinfo', '--transport=zeromq', '--output-columns=80', '--ssh', '--coverage-xml=/tmp/coverage.xml', '--xml=/tmp/xml-unittests-output'] failed
21:25:00 Build step 'Execute shell' marked build as failure
```

---

@rallytime commented on [Wed May 03 2017](https://github.com/saltstack/zh/issues/1281#issuecomment-298710450)

This is failing because the system-wide version of Python is still 2.6, and thus the version of pip is also 2.6. `pip2.7` is installed on the box, but `/usr/bin/pip` is still 2.6. So when the salt-jenkins states run, they all install with pip2.6, and not pip2.7, and the tests running with `python2.7 /testing/tests/runtest.py` fail because pytest-salt is installed under 2.6.

Waiting to hear back from @cachedout about what the plan is for this.

```
# salt-call --local pip.install apache-libcloud
local:
    ----------
    pid:
        25642
    retcode:
        0
    stderr:
        DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
    stdout:
        Requirement already satisfied: apache-libcloud in /usr/lib/python2.6/site-packages
```

**Comment by rallytime** [comment]
https://github.com/saltstack/salt/pull/41039 should help this out. I'm testing it now. :)

**Comment by rallytime** [comment]
Tests are running on CentOS 6 now!

**Comment by cachedout** [comment]
Nice work, @rallytime
