### ISSUE TITLE
[2017.5] Several distros failing integration.modules.test_state test on Python 3

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#342]
The `integration.modules.test_state.StateModuleTest.test_requisites_full_sls_import` is failing on the [2017.5 Python 3](https://jenkins.saltstack.com/job/branch_tests/job/2017.5/view/Python%203/) tests for several distros:
```
Traceback (most recent call last):
  File "//testing/tests/support/mixins.py", line 541, in assertSaltTrueReturn
    self.assertTrue(self.__getWithinSaltReturn(ret, 'result'))
  File "/usr/lib64/python3.4/unittest/case.py", line 657, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/testing/tests/integration/modules/test_state.py", line 763, in test_requisites_full_sls_import
    self.assertSaltTrueReturn(ret)
  File "//testing/tests/support/mixins.py", line 547, in assertSaltTrueReturn
    **(next(six.itervalues(ret)))
AssertionError: False is not True. Salt Comment:
The following requisites were not found:
                   require:
                       sls: requisites.fullsls_require_import2
```

This test is failing on the following distros:
- SUSE LEAP
- Ubuntu 17.04

**Comment by terminalmage** [comment]
This fails for me even on Python 2.

**Comment by rallytime** [comment]
Interesting. I haven't seen that on the Jenkins test runs themselves.

**Comment by garethgreenaway** [comment]
This is a weird one.  Running it once and it fails, running it again and it succeeds.

**Comment by cachedout** [comment]
@garethgreenaway Can you come back to this one in the morning? Loop in @terminalmage or @rallytime if you need some assistance.

**Comment by garethgreenaway** [comment]
@cachedout Will do.

**Comment by Ch3LL** [comment]
Correct me if i'm wrong but I believe these PRs will resolve this issue: https://github.com/saltstack/salt/pull/41614 and https://github.com/saltstack/salt/pull/41580

**Comment by garethgreenaway** [comment]
@Ch3LL Yup! Once those are merged in this one can get closed out.

**Comment by rallytime** [comment]
Back-port to Nitrogen is here: https://github.com/saltstack/salt/pull/41674
