### ISSUE TITLE
[2017.5] A couple of virtualenv integration tests are failing

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#347]
The `integration.modules.test_virtualenv` test file has about 3 tests failing on the [2017.5 Python 3](https://jenkins.saltstack.com/job/branch_tests/job/2017.5/view/Python%203/) tests. 

- [ ] `integration.modules.test_virtualenv.VirtualenvModuleTest.test_create_defaults`
```
Traceback (most recent call last):
  File "/testing/tests/integration/modules/test_virtualenv.py", line 34, in test_create_defaults
    self.assertTrue(os.path.exists(pip_file))
AssertionError: False is not true
```
- [ ] `integration.modules.test_virtualenv.VirtualenvModuleTest.test_site_packages`
```
Traceback (most recent call last):
  File "/testing/tests/integration/modules/test_virtualenv.py", line 45, in test_site_packages
    self.assertFalse(with_site == without_site)
AssertionError: True is not false
```
- [ ] `integration.modules.test_virtualenv.VirtualenvModuleTest.test_clear`
```
Traceback (most recent call last):
  File "/testing/tests/integration/modules/test_virtualenv.py", line 55, in test_clear
    self.assertFalse('pep8' in packages)
TypeError: argument of type 'bool' is not iterable
```

**Comment by terminalmage** [comment]
Fixed locally, PR forthcoming with other test fixes.

**Comment by terminalmage** [comment]
Fixed by https://github.com/saltstack/salt/pull/41293.
