### ISSUE TITLE
Get the Mac Tests to Run completely on 2017.5

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#372]
Currently the Mac tests are failing with the following error: 

```
11:59:36 Traceback (most recent call last):
11:59:36   File "/testing/tests/runtests.py", line 59, in <module>
11:59:36     from tests.integration import TestDaemon  # pylint: disable=W0403
11:59:36   File "/testing/tests/integration/__init__.py", line 35, in <module>
11:59:36     from tests.support.processes import *  # pylint: disable=wildcard-import
11:59:36   File "/testing/tests/support/processes.py", line 18, in <module>
11:59:36     from pytestsalt.utils import SaltRunEventListener as PytestSaltRunEventListener
11:59:36 ImportError: No module named pytestsalt.utils
```

I think i need to create a new image with pytest and any other test requirements installed.

**Comment by Ch3LL** [comment]
These two PRs should get the tests running on 2017.5 for mac: https://github.com/saltstack/salt-jenkins/pull/377 and https://github.com/saltstack/salt-jenkins/pull/376

**Comment by Ch3LL** [comment]
Confirmed both Mac10.11 and 10.12 are now running for python2 on nitrogen

**Comment by rallytime** [comment]
Nice job!
