### ISSUE TITLE
MacOSX 10.12 Fix test_harddisk_sleep test

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#380]
Currently the test `integration.modules.test_mac_power.MacPowerModuleTest.test_harddisk_sleep` is failing on MacOSX 10.12 on head of 2017.4 with following error:

```
Error Message

False is not true
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/support/helpers.py", line 86, in wrap
    return caller(cls)
  File "/testing/tests/integration/modules/test_mac_power.py", line 109, in test_harddisk_sleep
    self.assertTrue(self.run_function('power.set_harddisk_sleep', ['Off']))
AssertionError: False is not true
		
Standard Output

	
Standard Error
```

**Comment by Ch3LL** [comment]
This is not failing anymore. Will re-open if it does and see if its flaky.
