### ISSUE TITLE
MacOSX Fix test_list_present_inexistent_nested test

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#385]
Currently the test `unit.states.test_grains.GrainsTestCase.test_list_present_inexistent_nested` is failing on MacOSX on the head of nitrogen with the following error: 

```
Error Message

cannot represent an object: defaultdict(<function <lambda> at 0x110621cf8>, {'is': defaultdict(<function <lambda> at 0x110621cf8>, {'nested': ['baz']})})
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/unit/states/test_grains.py", line 916, in test_list_present_inexistent_nested
    value='baz')
  File "/testing/salt/states/grains.py", line 204, in list_present
    new_grains = __salt__['grains.append'](name, value)
  File "/testing/salt/modules/grains.py", line 370, in append
    return setval(key, grains)
  File "/testing/salt/modules/grains.py", line 313, in setval
    return setvals({key: val}, destructive)
  File "/testing/salt/modules/grains.py", line 269, in setvals
    cstr = yaml.safe_dump(grains, default_flow_style=False)
  File "/opt/salt/lib/python2.7/site-packages/yaml/__init__.py", line 218, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
  File "/opt/salt/lib/python2.7/site-packages/yaml/__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "/opt/salt/lib/python2.7/site-packages/yaml/representer.py", line 28, in represent
    node = self.represent_data(data)
  File "/opt/salt/lib/python2.7/site-packages/yaml/representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "/opt/salt/lib/python2.7/site-packages/yaml/representer.py", line 223, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "/opt/salt/lib/python2.7/site-packages/yaml/representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "/opt/salt/lib/python2.7/site-packages/yaml/representer.py", line 67, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/opt/salt/lib/python2.7/site-packages/yaml/representer.py", line 247, in represent_undefined
    raise RepresenterError("cannot represent an object: %s" % data)
RepresenterError: cannot represent an object: defaultdict(<function <lambda> at 0x110621cf8>, {'is': defaultdict(<function <lambda> at 0x110621cf8>, {'nested': ['baz']})})
		
Standard Output

	
Standard Error
```

**Comment by gtmanfred** [comment]
I am unable to replicate this

```
jk-sierra-base:salt root# python -m tests.runtests -n unit.states.test_grains.GrainsTestCase.test_list_present_inexistent_nested -vv
Found tests module not from salt in tests/__init__.py
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Python Version: 2.7.12 (default, Aug 24 2016, 14:05:14) [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
 * Transplanting configuration files to '/private/tmp/salt-tests-tmpdir/config'
 * Current Directory: /private/var/root/src/salt
 * Test suite is running under PID 2892
 * Logging tests on /private/tmp/salt-runtests.log
INFO
12:38:15,481 [tests.support.parser:460 ][INFO    ] Runtests logging has been setup
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Starting unit.states.test_grains.GrainsTestCase.test_list_present_inexistent_nested Tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test_list_present_inexistent_nested (unit.states.test_grains.GrainsTestCase)
[CPU:45.6%|MEM:70.6%]  ... ok

----------------------------------------------------------------------
Ran 1 test in 0.005s

OK

==========================================================================================================================================================================  Overall Tests Report  ==========================================================================================================================================================================
***  No Problems Found While Running Tests  ********************************************************************************************************************************************************************************************************************************************************************************************************************************
============================================================================================================================================================================================================================================================================================================================================================================
OK (total=1, skipped=0, passed=1, failures=0, errors=0)
==========================================================================================================================================================================  Overall Tests Report  ==========================================================================================================================================================================
12:38:15,532 [tests.support.parser                    :660 ][INFO    ] Test suite execution finalized with exit code: 0
```

Running a test to verify if jenkins works. http://mac-jenkins.lehi.saltstack.net:8080/job/2017.5/job/macOS-10.12/124/

**Comment by gtmanfred** [comment]
This fails on jenkins, but works locally.

**Comment by Ch3LL** [comment]
I was able to replicate this by running it with all unit tests. Try this: `python runtests.py -u`

**Comment by gtmanfred** [comment]
Narrowed down.

`python -m tests.runtests -n unit.loader.test_loader.LazyLoaderVirtualEnabledTest.test_disable -n unit.states.test_grains`

**Comment by gtmanfred** [comment]
We need to update pyyaml to 3.12 on the mac and this test works.
