### ISSUE TITLE
MacOSX Fix test_issue_1959_virtualenv_runas test

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#388]
Currently the test `integration.states.test_virtualenv.VirtualenvTest.test_issue_1959_virtualenv_runas` is failing on MacOSX with the following error:

```
Error Message

False is not True. Salt Comment: Created new virtualenv Collecting pep8==1.3.3 (from -r /tmp/tmpivWfSX/requirements.txt (line 1)) The directory '/private/var/root/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag. The directory '/var/root/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag. Exception: Traceback (most recent call last):   File "/private/tmp/issue-1959-virtualenv-runas/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main     status = self.run(options, args)   File "/private/tmp/issue-1959-virtualenv-runas/lib/python2.7/site-packages/pip/commands/install.py", line 324, in run     requirement_set.prepare_files(finder)   File "/private/tmp/issue-1959-virtualenv-runas/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files     ignore_dependencies=self.ignore_dependencies))   File "/private/tmp/issue-1959-virtualenv-runas/lib/python2.7/site-packages/pip/req/req_set.py", line 554, in _prepare_file     require_hashes   File "/private/tmp/issue-1959-virtualenv-runas/lib/python2.7/site-packages/pip/req/req_install.py", line 281, in populate_link     self.link = self._wheel_cache.cached_wheel(self.link, self.name)   File "/private/tmp/issue-1959-virtualenv-runas/lib/python2.7/site-packages/pip/wheel.py", line 68, in cached_wheel     self._cache_dir, link, self._format_control, package_name)   File "/private/tmp/issue-1959-virtualenv-runas/lib/python2.7/site-packages/pip/wheel.py", line 129, in cached_wheel     wheel_names = os.listdir(root) OSError: [Errno 13] Permission denied: '/var/root/Library/Caches/pip/wheels/a0/34/40/49fb457ed432cae290b1e16e8944118f1833a2488bf62414e8'
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/support/helpers.py", line 86, in wrap
    return caller(cls)
  File "/testing/tests/integration/states/test_virtualenv.py", line 44, in test_issue_1959_virtualenv_runas
    self.assertSaltTrueReturn(ret)
  File "/testing/tests/support/mixins.py", line 547, in assertSaltTrueReturn
    **(next(six.itervalues(ret)))
AssertionError: False is not True. Salt Comment:
Created new virtualenv
Collecting pep8==1.3.3 (from -r /tmp/tmpivWfSX/requirements.txt (line 1))
The directory '/private/var/root/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/var/root/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Exception:
Traceback (most recent call last):
  File "/private/tmp/issue-1959-virtualenv-runas/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/private/tmp/issue-1959-virtualenv-runas/lib/python2.7/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/private/tmp/issue-1959-virtualenv-runas/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/private/tmp/issue-1959-virtualenv-runas/lib/python2.7/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/private/tmp/issue-1959-virtualenv-runas/lib/python2.7/site-packages/pip/req/req_install.py", line 281, in populate_link
    self.link = self._wheel_cache.cached_wheel(self.link, self.name)
  File "/private/tmp/issue-1959-virtualenv-runas/lib/python2.7/site-packages/pip/wheel.py", line 68, in cached_wheel
    self._cache_dir, link, self._format_control, package_name)
  File "/private/tmp/issue-1959-virtualenv-runas/lib/python2.7/site-packages/pip/wheel.py", line 129, in cached_wheel
    wheel_names = os.listdir(root)
OSError: [Errno 13] Permission denied: '/var/root/Library/Caches/pip/wheels/a0/34/40/49fb457ed432cae290b1e16e8944118f1833a2488bf62414e8'
```

**Comment by gtmanfred** [comment]
Fixed, this is caused by mac_user.add not creating the home directory.
