### ISSUE TITLE
MacOSX Fix test_clean_old_jobs test

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#393]
Currently the test `unit.returners.test_local_cache.Local_CacheTest.test_clean_old_jobs` is failing on MacOSX on the head of nitrogen with the following error:

```
Error Message

1
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/unit/returners/test_local_cache.py", line 246, in test_clean_old_jobs
    self._add_job()
  File "/testing/tests/unit/returners/test_local_cache.py", line 236, in _add_job
    add_job = salt.utils.job.store_job(opts, load)
  File "/testing/salt/utils/job.py", line 28, in store_job
    mminion = salt.minion.MasterMinion(opts, states=False, rend=False)
  File "/testing/salt/minion.py", line 738, in __init__
    self.opts = salt.config.minion_config(opts['conf_file'], ignore_config_errors=ignore_config_errors)
  File "/testing/salt/config/__init__.py", line 2131, in minion_config
    overrides = load_config(path, env_var, DEFAULT_MINION_OPTS['conf_file'])
  File "/testing/salt/config/__init__.py", line 1997, in load_config
    sys.exit(salt.defaults.exitcodes.EX_GENERIC)
SystemExit: 1
		
Standard Output

	
Standard Error

```

**Comment by Ch3LL** [comment]
probably directly related to: https://github.com/saltstack/salt-jenkins/issues/394

**Comment by Ch3LL** [comment]
upgrading to pyyaml 3.12 worked to get the tests running. Thanks to @gtmanfred for the suggestion. I owe him a :beer:

Will work on adding this requirement to the salt-jenkins states after fixing another mac issue i'm working on
