### ISSUE TITLE
MacOSX Fix test_not_clean_new_jobs test

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#394]
Currently the test `unit.returners.test_local_cache.Local_CacheTest.test_not_clean_new_jobs` is failing on MacOSX on the head of nitrogen with the following error:

```
Error Message

1
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/unit/returners/test_local_cache.py", line 260, in test_not_clean_new_jobs
    self._add_job()
  File "/testing/tests/unit/returners/test_local_cache.py", line 236, in _add_job
    add_job = salt.utils.job.store_job(opts, load)
  File "/testing/salt/utils/job.py", line 28, in store_job
    mminion = salt.minion.MasterMinion(opts, states=False, rend=False)
  File "/testing/salt/minion.py", line 738, in __init__
    self.opts = salt.config.minion_config(opts['conf_file'], ignore_config_errors=ignore_config_errors)
  File "/testing/salt/config/__init__.py", line 2131, in minion_config
    overrides = load_config(path, env_var, DEFAULT_MINION_OPTS['conf_file'])
  File "/testing/salt/config/__init__.py", line 1997, in load_config
    sys.exit(salt.defaults.exitcodes.EX_GENERIC)
SystemExit: 1
		
Standard Output

	
Standard Error
```

**Comment by Ch3LL** [comment]
This is failing because its not able to parse the config file. I'm seeing this error:

```
12:50:29,063 [tests.support.unit                                        :382 ][DEBUG   ] >>>>> START >>>>> unit.returners.test_local_cache.Local_CacheTest.test_not_clean_new_jobs
12:50:29,063 [salt.config                                               :1889][DEBUG   ] Reading configuration from /private/tmp/salt-tests-tmpdir/config/master
12:50:29,126 [salt.config                                               :1889][DEBUG   ] Reading configuration from /private/tmp/salt-tests-tmpdir/tmpiWlYqs/conf/master
12:50:29,189 [salt.config                                               :1895][ERROR   ] Error parsing configuration file: /private/tmp/salt-tests-tmpdir/tmpiWlYqs/conf/master - could not de
termine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "<string>", line 2, column 1:
    !!python/unicode 'aliases.file': ... 
    ^
12:50:29,190 [salt.config                                               :1994][ERROR   ] Error parsing configuration file: /private/tmp/salt-tests-tmpdir/tmpiWlYqs/conf/master - could not de
termine a constructor for the tag 'tag:yaml.org,2002:python/unicode'
  in "<string>", line 2, column 1:
    !!python/unicode 'aliases.file': ... 
    ^
12:50:29,191 [tests.support.unit                                        :386 ][DEBUG   ] <<<<< END <<<<<<< unit.returners.test_local_cache.Local_CacheTest.test_not_clean_new_jobs
```

I think its related to https://github.com/saltstack/salt/pull/38554 but reverting PR does not help

I'm going to take a break from this one and re-visit with a clearer mind but I might be stuck on this one, since I am new to the yaml code.
