### ISSUE TITLE
[Python 3 Macosx] Fix integration.modules.test_cp.CPModuleTest.test_get_file_str_https

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#404]
Currently the test `integration.modules.test_cp.CPModuleTest.test_get_file_str_https ` is failing on MacOSX with the error:

```
Error Message

'Bootstrap' not found in 'The minion function caused an exception: Traceback (most recent call last):\n  File "/testing/salt/minion.py", line 1451, in _thread_return\n    return_data = executor.execute()\n  File "/testing/salt/executors/direct_call.py", line 28, in execute\n    return self.func(*self.args, **self.kwargs)\n  File "/testing/salt/modules/cp.py", line 388, in get_file_str\n    data = fp_.read()\n  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode\n    return codecs.ascii_decode(input, self.errors)[0]\nUnicodeDecodeError: \'ascii\' codec can\'t decode byte 0xc2 in position 5400: ordinal not in range(128)\n'
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/integration/modules/test_cp.py", line 356, in test_get_file_str_https
    self.assertIn('Bootstrap', ret)
AssertionError: 'Bootstrap' not found in 'The minion function caused an exception: Traceback (most recent call last):\n  File "/testing/salt/minion.py", line 1451, in _thread_return\n    return_data = executor.execute()\n  File "/testing/salt/executors/direct_call.py", line 28, in execute\n    return self.func(*self.args, **self.kwargs)\n  File "/testing/salt/modules/cp.py", line 388, in get_file_str\n    data = fp_.read()\n  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode\n    return codecs.ascii_decode(input, self.errors)[0]\nUnicodeDecodeError: \'ascii\' codec can\'t decode byte 0xc2 in position 5400: ordinal not in range(128)\n'
```

**Comment by Ch3LL** [comment]
Fixed by https://github.com/saltstack/salt-jenkins/pull/425
