### ISSUE TITLE
[Python 3 MacOSX] Fix integration.modules.test_cp.CPModuleTest.test_get_file_str_local 

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#405]
Error Message

>"KNIGHT:  They're nervous, sire." not found in 'The minion function caused an exception: Traceback (most recent call last):\n  File "/testing/salt/minion.py", line 1451, in _thread_return\n    return_data = executor.execute()\n  File "/testing/salt/executors/direct_call.py", line 28, in execute\n    return self.func(*self.args, **self.kwargs)\n  File "/testing/salt/modules/cp.py", line 388, in get_file_str\n    data = fp_.read()\n  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode\n    return codecs.ascii_decode(input, self.errors)[0]\nUnicodeDecodeError: \'ascii\' codec can\'t decode byte 0xe2 in position 974: ordinal not in range(128)\n'

**Comment by Ch3LL** [comment]
Fixed by https://github.com/saltstack/salt-jenkins/pull/425
