### ISSUE TITLE
[Python 3 MacOSX] Fix multiple test_cp tests

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#407]
The following tests have the same error:
integration.modules.test_cp.CPModuleTest.test_get_url_file 
integration.modules.test_cp.CPModuleTest.test_get_file_gzipped
integration.modules.test_cp.CPModuleTest.test_get_url_https
integration.modules.test_cp.CPModuleTest.test_get_url_https_dest_empty

Error Message

> 'ascii' codec can't decode byte 0xe2 in position 974: ordinal not in range(128)

Stacktrace

>Traceback (most recent call last):
  File "/testing/tests/integration/modules/test_cp.py", line 74, in test_get_file_gzipped
    data = fp_.read()
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 974: ordinal not in range(128)

**Comment by Ch3LL** [comment]
Fixed by https://github.com/saltstack/salt-jenkins/pull/425
