### ISSUE TITLE
[Python 3 MacOSX] Fix integration.modules.test_mac_power.MacPowerModuleTest.test_display_sleep

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#413]
Error Message

> False is not true

Stacktrace

>Traceback (most recent call last):
  File "/testing/tests/support/helpers.py", line 86, in wrap
    return caller(cls)
  File "/testing/tests/integration/modules/test_mac_power.py", line 81, in test_display_sleep
    self.assertTrue(self.run_function('power.set_display_sleep', ['Off']))
AssertionError: False is not true

**Comment by Ch3LL** [comment]
Flaky Test. Closing
