### ISSUE TITLE
[Python 3 MacOSX] Fix integration.modules.test_state.StateModuleTest.test_requisites_prereq_simple_ordering_and_errors

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#414]
Error Message

>'list' object has no attribute 'items'

Stacktrace

>Traceback (most recent call last):
  File "/testing/tests/integration/modules/test_state.py", line 887, in test_requisites_prereq_simple_ordering_and_errors
    result = self.normalize_ret(ret)
  File "/testing/tests/integration/modules/test_state.py", line 594, in normalize_ret
    for item, descr in six.iteritems(ret):
  File "/testing/salt/ext/six.py", line 588, in iteritems
    return iter(d.items(**kw))
AttributeError: 'list' object has no attribute 'items'

**Comment by Ch3LL** [comment]
This is the reason it can't iterate the ret. The ret is the following:

```
'Rendering SLS requisites.prereq_simple2 failed, render error: \'ascii\' codec can\'t decode byte 0xc2 in position 165: ordinal not in range(128)\nTraceback (most recent call last):\n  File
 "/testing/salt/state.py", line 3180, in render_state\n    rendered_sls=mods\n  File "/testing/salt/template.py", line 82, in compile_template\n    render_pipe = template_shebang(template, r
enderers, default, blacklist, whitelist, input_data)\n  File "/testing/salt/template.py", line 172, in template_shebang\n    line = ifile.readline()\n  File "/usr/local/Cellar/python3/3.6.1/
Frameworks/Python.framework/Versions/3.6/lib/python3.6/encodings/ascii.py", line 26, in decode\n    return codecs.ascii_decode(input, self.errors)[0]\nUnicodeDecodeError: \'ascii\' codec can
\'t decode byte 0xc2 in position 165: ordinal not in range(128)\n']
```

So diving into that error now

**Comment by Ch3LL** [comment]
Fixed by https://github.com/saltstack/salt-jenkins/pull/425
