### ISSUE TITLE
[Python 3 MacOSX] Fix integration.modules.test_archive.ArchiveTest Unicode Errors

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#415]
The following tests are failing with the same error:

integration.modules.test_archive.ArchiveTest.test_unzip
integration.modules.test_archive.ArchiveTest.test_tar_pack
integration.modules.test_archive.ArchiveTest.test_gunzip
integration.modules.test_archive.ArchiveTest.test_cmd_unzip

Error Message

>'ascii' codec can't encode character '\xf6' in position 100: ordinal not in range(128)

Stacktrace

>Traceback (most recent call last):
  File "/testing/tests/integration/modules/test_archive.py", line 200, in test_cmd_unzip
    self._set_up(arch_fmt='zip')
  File "/testing/tests/integration/modules/test_archive.py", line 80, in _set_up
    '''))
UnicodeEncodeError: 'ascii' codec can't encode character '\xf6' in position 100: ordinal not in range(128)

**Comment by Ch3LL** [comment]
This will be fixed by whatever is fixed in this comment https://github.com/saltstack/salt/pull/41664#issuecomment-307484874

**Comment by Ch3LL** [comment]
Fixed by https://github.com/saltstack/salt-jenkins/pull/425
