### ISSUE TITLE
[Python 3 MacOSX] Fix integration.modules.test_archive.ArchiveTest AttributeError

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#416]
The following tests are failing with the same error:

integration.modules.test_archive.ArchiveTest.test_cmd_zip
integration.modules.test_archive.ArchiveTest.test_gzip
integration.modules.test_archive.ArchiveTest.test_tar_unpack 
integration.modules.test_archive.ArchiveTest.test_zip

Error Message

>'ArchiveTest' object has no attribute 'src'

Stacktrace

>Traceback (most recent call last):
  File "/testing/tests/integration/modules/test_archive.py", line 215, in test_zip
    self._set_up(arch_fmt='zip')
  File "/testing/tests/integration/modules/test_archive.py", line 61, in _set_up
    os.makedirs(self.src)
AttributeError: 'ArchiveTest' object has no attribute 'src'

**Comment by Ch3LL** [comment]
This will be fixed by whatever is decided by this comment: https://github.com/saltstack/salt/pull/41664#issuecomment-307484874

**Comment by Ch3LL** [comment]
Fixed by https://github.com/saltstack/salt-jenkins/pull/425
