### ISSUE TITLE
[Python 3] Fix unit.utils.test_etcd_util tests

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#432]
Currently the following tests are failing on Centos7:

unit.utils.test_etcd_util.EtcdUtilTestCase.test_get
unit.utils.test_etcd_util.EtcdUtilTestCase.test_ls
unit.utils.test_etcd_util.EtcdUtilTestCase.test_tree
unit.utils.test_etcd_util.EtcdUtilTestCase.test_watch

Here is the stacktrace/error:

```
Error Message

'EtcdKeyNotFound' object is not iterable
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/unit/utils/test_etcd_util.py", line 92, in test_get
    self.assertEqual(client.get('not-found'), None)
  File "/testing/salt/utils/etcd_util.py", line 177, in get
    result = self.read(key, recursive=recurse)
  File "<string>", line 3, in read
  File "/usr/lib64/python3.4/unittest/mock.py", line 902, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/lib64/python3.4/unittest/mock.py", line 955, in _mock_call
    effect = self.side_effect
  File "/usr/lib64/python3.4/unittest/mock.py", line 507, in __get_side_effect
    sf = _MockIter(sf)
  File "/usr/lib64/python3.4/unittest/mock.py", line 349, in __init__
    self.obj = iter(obj)
TypeError: 'EtcdKeyNotFound' object is not iterable
```

https://jenkins.saltstack.com/job/branch_tests/job/2017.7/view/Python%203/job/salt-linode-py3-cent7/131/

**Comment by DmitryKuzmenko** [comment]
Fixed by https://github.com/saltstack/salt/pull/41859
