### ISSUE TITLE
[Python 3] Fix unit.modules.test_djangomod.DjangomodCliCommandTestCase.test_django_admin_cli_createsuperuser 

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#433]
Currently the test `unit.modules.test_djangomod.DjangomodCliCommandTestCase.test_django_admin_cli_createsuperuser ` is failing on Fedora24 

```
Error Message

assert_called_once
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/unit/modules/test_djangomod.py", line 192, in test_django_admin_cli_createsuperuser
    mock.assert_called_once()
  File "/usr/lib64/python3.5/unittest/mock.py", line 585, in __getattr__
    raise AttributeError(name)
AttributeError: assert_called_once
```

https://jenkins.saltstack.com/job/branch_tests/job/2017.7/view/Python%203/job/salt-linode-py3-fedora24/135/testReport/junit/unit.modules.test_djangomod/DjangomodCliCommandTestCase/test_django_admin_cli_createsuperuser/

**Comment by Ch3LL** [comment]
This should be fixed by https://github.com/saltstack/salt/pull/41850
