### ISSUE TITLE
[Python 3] Fix unit.modules.test_mdadm.MdadmTestCase.test_create

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#436]
The test `unit.modules.test_mdadm.MdadmTestCase.test_create` is failing on Fedora 25

```
Error Message

Expected call: mock(['mdadm', '-C', '/dev/md0', '-R', '-v', '--force', '--chunk', '256', '-l', '5', '-e', 'default', '-n', '3', '/dev/sdb1', '/dev/sdc1', '/dev/sdd1'], python_shell=False) Actual call: mock(['mdadm', '-C', '/dev/md0', '-R', '-v', '--chunk', '256', '--force', '-l', '5', '-e', 'default', '-n', '3', '/dev/sdb1', '/dev/sdc1', '/dev/sdd1'], python_shell=False)
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/unit/modules/test_mdadm.py", line 68, in test_create
    mock.assert_called_once_with(expected_args, python_shell=False)
  File "/usr/lib64/python3.5/unittest/mock.py", line 805, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/usr/lib64/python3.5/unittest/mock.py", line 794, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: Expected call: mock(['mdadm', '-C', '/dev/md0', '-R', '-v', '--force', '--chunk', '256', '-l', '5', '-e', 'default', '-n', '3', '/dev/sdb1', '/dev/sdc1', '/dev/sdd1'], python_shell=False)
Actual call: mock(['mdadm', '-C', '/dev/md0', '-R', '-v', '--chunk', '256', '--force', '-l', '5', '-e', 'default', '-n', '3', '/dev/sdb1', '/dev/sdc1', '/dev/sdd1'], python_shell=False)
```

https://jenkins.saltstack.com/job/branch_tests/job/2017.7/view/Python%203/job/salt-linode-py3-fedora25/107/testReport/junit/unit.modules.test_mdadm/MdadmTestCase/test_create/

**Comment by DmitryKuzmenko** [comment]
Fixed by https://github.com/saltstack/salt/pull/41874
