### ISSUE TITLE
[Python 3] Fix unit.modules.test_disk.DiskTestCase.test_tune

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#437]
The test `unit.modules.test_disk.DiskTestCase.test_tune` is failing on suse42

```
Error Message

Expected call: mock('blockdev --setra 512 --setfra 512 /dev/sda', python_shell=False) Actual call: mock('blockdev --setfra 512 --setra 512 /dev/sda', python_shell=False)
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/unit/modules/test_disk.py", line 131, in test_tune
    python_shell=False
  File "/usr/lib64/python3.4/unittest/mock.py", line 788, in assert_called_once_with
    return self.assert_called_with(*args, **kwargs)
  File "/usr/lib64/python3.4/unittest/mock.py", line 777, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: Expected call: mock('blockdev --setra 512 --setfra 512 /dev/sda', python_shell=False)
Actual call: mock('blockdev --setfra 512 --setra 512 /dev/sda', python_shell=False)
```

https://jenkins.saltstack.com/job/branch_tests/job/2017.7/view/Python%203/job/salt-linode-py3-opensuse42/128/testReport/junit/unit.modules.test_disk/DiskTestCase/test_tune/

**Comment by DmitryKuzmenko** [comment]
Fixed by https://github.com/saltstack/salt/pull/41872
