### ISSUE TITLE
decorator tests failing on python3

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#460]
The following tests:

```
integration.modules.test_decorators.DecoratorTest.test_depends
integration.modules.test_decorators.DecoratorTest.test_depends_will_not_fallback
integration.modules.test_decorators.DecoratorTest.test_missing_depends_will_fallback
```

Are failing within the test suite like so:

```
======================================================================  Overall Tests Report  =======================================================================
*** integration.modules.test_decorators.DecoratorTest Tests  ********************************************************************************************************
 --------  Failed Tests  --------------------------------------------------------------------------------------------------------------------------------------------
   -> integration.modules.test_decorators.DecoratorTest.test_depends  ...............................................................................................
       Traceback (most recent call last):                                                                                                                            
         File "/testing/tests/integration/modules/test_decorators.py", line 20, in test_depends                                                                      
           self.assertTrue(isinstance(ret, dict))                                                                                                                    
       AssertionError: False is not true                                                                                                                             
   ..................................................................................................................................................................
   -> integration.modules.test_decorators.DecoratorTest.test_depends_will_not_fallback  .............................................................................
       Traceback (most recent call last):                                                                                                                            
         File "/testing/tests/integration/modules/test_decorators.py", line 48, in test_depends_will_not_fallback                                                    
           self.assertTrue(isinstance(ret, dict))                                 
       AssertionError: False is not true 
   ..................................................................................................................................................................
   -> integration.modules.test_decorators.DecoratorTest.test_missing_depends_will_fallback  .........................................................................
       Traceback (most recent call last):
         File "/testing/tests/integration/modules/test_decorators.py", line 56, in test_missing_depends_will_fallback                                                
           'runtests_decorators.missing_depends_will_fallback'                    
       AssertionError: Second sequence is not a list: "'runtests_decorators.missing_depends_will_fallback' is not available."                                        
   ..................................................................................................................................................................
 --------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

they are failing on python 3 versions of mac, arch, ubuntu16, and ubuntu17.

Git bisect shows commit `0a0c6287a426f9f62b27de6a2a2b0cbf73214a3a` which is pr https://github.com/saltstack/salt/pull/42470

**Comment by rallytime** [comment]
This is fixed now.
