### ISSUE TITLE
Fix failing boto tests (again!)

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#526]
A bunch of boto tests started failing over night. Likely due to a new version released by moto or boto or something. Here's the trace back information:
```
Error Message

'pyOpenSSL' module missing required functionality. Try upgrading to v0.14 or newer.
Stacktrace

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/moto/core/models.py", line 72, in wrapper
    self.stop()
  File "/usr/local/lib/python2.7/dist-packages/moto/core/models.py", line 64, in stop
    self.disable_patching()
  File "/usr/local/lib/python2.7/dist-packages/moto/core/models.py", line 118, in disable_patching
    HTTPretty.disable()
  File "/usr/local/lib/python2.7/dist-packages/moto/packages/httpretty/core.py", line 1023, in disable
    inject_into_urllib3()
  File "/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 112, in inject_into_urllib3
    _validate_dependencies_met()
  File "/usr/local/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 147, in _validate_dependencies_met
    raise ImportError("'pyOpenSSL' module missing required functionality. "
ImportError: 'pyOpenSSL' module missing required functionality. Try upgrading to v0.14 or newer.
```

**Comment by rallytime** [comment]
This is fixed in the `2017.7` branch of `salt-jenkins`. Once the #530 is merged, that will fix `2016.11` failures, and #531 will fix the failures on `develop` and pull requests.
