### ISSUE TITLE
[develop] Py3 tests are running out of file handles

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#548]
Within the last week or so, the Python 3 tests started running out of file handles. This is most noticeable on pull requests, as they were previously passing most of the time.

Occasionally I see the `unit.utils.test_verify.TestVerify.test_max_open_files` test fail, but more often than not the test bails and fails before we get to that test and can output the results. The following PRs were made by @terminalmage to help with the situation, but it appears there is a deeper problem involved.

This issue is to track work on getting this fixed.

Refs https://github.com/saltstack/salt/pull/44442 and https://github.com/saltstack/salt-jenkins/pull/546

The following stacktrace is presented at the end of the test run (which was taken from the fix in https://github.com/saltstack/salt/pull/44442 _after_ #546 was merged):
```
22:25:16 OSError: [Errno 24] Too many open files: '/proc/stat'
22:25:16 Traceback (most recent call last):
22:25:16   File "/testing/tests/runtests.py", line 814, in <module>
22:25:16     main()
22:25:16   File "/testing/tests/runtests.py", line 799, in main
22:25:16     status = parser.run_unit_tests()
22:25:16   File "/testing/tests/runtests.py", line 734, in run_unit_tests
22:25:16     os.path.join(TEST_DIR, 'unit'), 'Unit', suffix='test_*.py'
22:25:16   File "/testing/tests/support/parser/__init__.py", line 511, in run_suite
22:25:16     ).run(tests)
22:25:16   File "/testing/tests/support/xmlunit.py", line 85, in run
22:25:16     result = xmlrunner.runner.XMLTestRunner.run(self, test)
22:25:16   File "/usr/local/lib/python3.5/dist-packages/xmlrunner/runner.py", line 66, in run
22:25:16     test(result)
22:25:16   File "/usr/lib/python3.5/unittest/suite.py", line 84, in __call__
22:25:16     return self.run(*args, **kwds)
22:25:16   File "/usr/lib/python3.5/unittest/suite.py", line 122, in run
22:25:16     test(result)
22:25:16   File "/usr/lib/python3.5/unittest/suite.py", line 84, in __call__
22:25:16     return self.run(*args, **kwds)
22:25:16   File "/usr/lib/python3.5/unittest/suite.py", line 122, in run
22:25:16     test(result)
22:25:16   File "/usr/lib/python3.5/unittest/suite.py", line 84, in __call__
22:25:16     return self.run(*args, **kwds)
22:25:16   File "/usr/lib/python3.5/unittest/suite.py", line 122, in run
22:25:16     test(result)
22:25:16   File "/usr/lib/python3.5/unittest/case.py", line 648, in __call__
22:25:16     return self.run(*args, **kwds)
22:25:16   File "/testing/tests/support/unit.py", line 192, in run
22:25:16     outcome = super(TestCase, self).run(result=result)
22:25:16   File "/usr/lib/python3.5/unittest/case.py", line 608, in run
22:25:16     self._feedErrorsToResult(result, outcome.errors)
22:25:16   File "/usr/lib/python3.5/unittest/case.py", line 538, in _feedErrorsToResult
22:25:16     result.addError(test, exc_info)
22:25:16   File "/usr/lib/python3.5/unittest/result.py", line 17, in inner
22:25:16   File "/usr/local/lib/python3.5/dist-packages/xmlrunner/result.py", line 249, in addError
22:25:16   File "/usr/local/lib/python3.5/dist-packages/xmlrunner/result.py", line 101, in __init__
22:25:16   File "/usr/lib/python3.5/unittest/runner.py", line 45, in getDescription
22:25:16   File "/testing/tests/support/unit.py", line 218, in shortDescription
22:25:16     proc_info = '[CPU:{0}%|MEM:{1}%'.format(psutil.cpu_percent(),
22:25:16   File "/usr/local/lib/python3.5/dist-packages/psutil/__init__.py", line 1813, in cpu_percent
22:25:16   File "/usr/local/lib/python3.5/dist-packages/psutil/__init__.py", line 1685, in cpu_times
22:25:16   File "/usr/local/lib/python3.5/dist-packages/psutil/_pslinux.py", line 557, in cpu_times
22:25:16   File "/usr/local/lib/python3.5/dist-packages/psutil/_pslinux.py", line 190, in open_binary
22:25:16 OSError: [Errno 24] Too many open files: '/proc/stat'
```

**Comment by rallytime** [comment]
Some work is being done for this in https://github.com/saltstack/salt/pull/44442. Let's see how that test run goes.

**Comment by terminalmage** [comment]
These should be fixed now. There was a test that was setting the max number of open files artificially low for purposes of testing, and then opening a bunch of files in a directory. There was a `finally` block that cleaned up the temp directory where the files were being opened, but the act of performing a `shutil.rmtree()` on Python 3 apparently opens a filehandle which led to an OSError being raised. Since the `finally` block raised an exception before the original max open files value could be restored, this led to this value remaining artificially low for the remainder of the test run.

This has been fixed by moving the `shutil.rmtree()` after the function call which restores the original max open files value.

**Comment by rallytime** [comment]
🎉  Yay!
