### ISSUE TITLE
[develop] Test unit.grains.test_core.CoreGrainsTestCase.test_linux_memdata failing on Centos6

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#556]
The test `unit.grains.test_core.CoreGrainsTestCase.test_linux_memdata` is failing on centos6 in develop.

Here is the error: 

```
Traceback (most recent call last):
  File "/testing/tests/unit/grains/test_core.py", line 548, in test_linux_memdata
    os_grains = core.os_data()
  File "/testing/salt/grains/core.py", line 1761, in os_data
    osarch = __salt__['cmd.run']('rpm --eval %{_host_cpu}').strip()
  File "/usr/lib/python2.7/site-packages/mock.py", line 955, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mock.py", line 1018, in _mock_call
    ret_val = effect(*args, **kwargs)
  File "/testing/tests/unit/grains/test_core.py", line 488, in <lambda>
    side_effect=lambda x: _cmd_run_map[x]
KeyError: 'rpm --eval %{_host_cpu}'
```

https://jenkins.saltstack.com/job/branch_tests/job/develop/job/salt-linode-cent6/3442/testReport/junit/unit.grains.test_core/CoreGrainsTestCase/test_linux_memdata/

ping @garethgreenaway mind taking a look at this failure?

**Comment by terminalmage** [comment]
Fixed by https://github.com/saltstack/salt/pull/44704.
