### ISSUE TITLE
Multiple tests in unit.config.test_config.ConfigTestCase Fail on Centos7

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#558]
The following tests are failling on centos7 develop

```
unit.config.test_config.ConfigTestCase.test_cloud_config_deploy_scripts_search_path
unit.config.test_config.ConfigTestCase.test_cloud_config_double_profiles_path
unit.config.test_config.ConfigTestCase.test_cloud_config_double_providers_path
unit.config.test_config.ConfigTestCase.test_cloud_config_providers_in_opts
unit.config.test_config.ConfigTestCase.test_cloud_config_providers_in_opts_path
unit.config.test_config.ConfigTestCase.test_common_prefix_stripping
unit.config.test_config.ConfigTestCase.test_default_root_dir_included_in_config_root_dir
unit.config.test_config.ConfigTestCase.test_deploy_search_path_as_string
unit.config.test_config.ConfigTestCase.test_issue_5970_minion_confd_inclusion
unit.config.test_config.ConfigTestCase.test_load_client_config_from_environ_var
unit.config.test_config.ConfigTestCase.test_load_cloud_config_from_environ_var
unit.config.test_config.ConfigTestCase.test_load_master_config_from_environ_var
unit.config.test_config.ConfigTestCase.test_load_minion_config_from_environ_var
unit.config.test_config.ConfigTestCase.test_master_confd_inclusion
unit.config.test_config.ConfigTestCase.test_master_file_roots_glob
unit.config.test_config.ConfigTestCase.test_master_id_function
unit.config.test_config.ConfigTestCase.test_master_pillar_roots_glob
unit.config.test_config.ConfigTestCase.test_minion_file_roots_glob
unit.config.test_config.ConfigTestCase.test_minion_id_function
unit.config.test_config.ConfigTestCase.test_minion_pillar_roots_glob
unit.config.test_config.ConfigTestCase.test_proper_path_joining
unit.config.test_config.ConfigTestCase.test_sha256_is_default_for_master
unit.config.test_config.ConfigTestCase.test_sha256_is_default_for_minion
```

with this error:

```
Traceback (most recent call last):
  File "/testing/tests/unit/config/test_config.py", line 624, in test_cloud_config_providers_in_opts
    providers_config='bar')
  File "/usr/lib64/python2.7/unittest/case.py", line 513, in assertRaises
    callableObj(*args, **kwargs)
  File "/testing/salt/config/__init__.py", line 2581, in cloud_config
    master_config = salt.config.master_config(master_config_path)
  File "/testing/salt/config/__init__.py", line 3714, in master_config
    opts = apply_master_config(overrides, defaults)
  File "/testing/salt/config/__init__.py", line 3774, in apply_master_config
    cache_minion_id=None)
  File "/testing/salt/config/__init__.py", line 3517, in get_id
    newid = salt.utils.network.generate_minion_id()
  File "/testing/salt/utils/network.py", line 171, in generate_minion_id
    return _generate_minion_id().first() or 'localhost'
  File "/testing/salt/utils/network.py", line 161, in _generate_minion_id
    return hosts.extend([addr for addr in ip_addrs()
  File "/testing/salt/utils/network.py", line 1170, in ip_addrs
    return _ip_addrs(interface, include_loopback, interface_data, 'inet')
  File "/testing/salt/utils/network.py", line 1145, in _ip_addrs
    else interfaces()
  File "/testing/salt/utils/network.py", line 935, in interfaces
    return linux_interfaces()
  File "/testing/salt/utils/network.py", line 813, in linux_interfaces
    stderr=subprocess.STDOUT).communicate()[0]
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1224, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
```

https://jenkins.saltstack.com/job/branch_tests/job/develop/job/salt-linode-cent7/3474/#showFailuresLink

**Comment by rallytime** [comment]
This just barely started popping up within the last day or so (not sure if that information is helpful). Because as of yesterday, there were only 2 tests failing, which I fixed in https://github.com/saltstack/salt/pull/44543. 😞

**Comment by terminalmage** [comment]
Not seeing these failing now.

**Comment by rallytime** [comment]
Me either.
