### ISSUE TITLE
[python3] Flaky Tests Result in The salt master could not be contacted error

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#563]
Sometimes the python3 tests fail with the error:

```
Stacktrace

Traceback (most recent call last):
  File "/testing/salt/client/__init__.py", line 336, in run_job
    **kwargs)
  File "/testing/salt/client/__init__.py", line 1772, in pub
    raise SaltClientError
salt.exceptions.SaltClientError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/testing/tests/integration/loader/test_ext_modules.py", line 38, in test_overridden_internal
    funcs = self.run_function('sys.list_functions')
  File "//testing/tests/support/case.py", line 714, in run_function
    kwarg=kwargs)
  File "/testing/salt/client/__init__.py", line 723, in cmd
    **kwargs)
  File "/testing/salt/client/__init__.py", line 340, in run_job
    'The salt master could not be contacted. Is master running?'
salt.exceptions.SaltClientError: The salt master could not be contacted. Is master running?
```

For this test run: https://jenkins.saltstack.com/job/branch_tests/job/2017.7/view/Python%203/job/salt-lin-py3-ubuntu16/362/

these tests fail, but other failed runs included other tests too, its different each time:

```
integration.loader.test_ext_modules.LoaderOverridesTest.test_overridden_internal
integration.netapi.rest_cherrypy.test_app_pam.TestAuthPAM.test_bad_pwd_pam_chsh_service
integration.netapi.rest_cherrypy.test_app_pam.TestAuthPAM.test_bad_pwd_pam_login_service
integration.netapi.rest_cherrypy.test_app_pam.TestAuthPAM.test_good_pwd_pam_chsh_service
integration.netapi.rest_cherrypy.test_app_pam.TestAuthPAM.test_good_pwd_pam_login_service
integration.renderers.test_pydsl.PyDSLRendererIncludeTestCase.test_rendering_includes
integration.loader.test_ext_grains.LoaderGrainsTest.test_grains_overwrite
integration.modules.test_state.StateModuleTest.test_exclude
```

**Comment by sagetherage** [comment]
@Ch3LL is this still an issue and we should re-label?

**Comment by Ch3LL** [comment]
i havne't seen it for a while so i'll close and we can re-open if needed
