### ISSUE TITLE
[develop][python3] proxy tests failing on python3 on develop

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#564]
Here is the error:

```
Traceback (most recent call last):
  File "/testing/salt/client/__init__.py", line 1807, in pub
    raise SaltReqTimeoutError()
salt.exceptions.SaltReqTimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/testing/salt/client/__init__.py", line 338, in run_job
    **kwargs)
  File "/testing/salt/client/__init__.py", line 1811, in pub
    u'Salt request timed out. The master is not responding. You '
salt.exceptions.SaltReqTimeoutError: Salt request timed out. The master is not responding. You may need to run your command with `--async` in order to bypass the congested event bus. With `--async`, the CLI tool will print the job id (jid) and exit immediately without listening for responses. You can then use `salt-run jobs.lookup_jid` to look up the results of the job in the job cache later.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/testing/tests/integration/proxy/test_simple.py", line 39, in test_install_pkgs
    ret = self.run_function('pkg.install', ['thispkg'], minion_tgt='proxytest')
  File "/testing/tests/support/case.py", line 716, in run_function
    kwarg=kwargs)
  File "/testing/salt/client/__init__.py", line 728, in cmd
    **kwargs)
  File "/testing/salt/client/__init__.py", line 346, in run_job
    raise SaltClientError(general_exception)
salt.exceptions.SaltClientError: Salt request timed out. The master is not responding. You may need to run your command with `--async` in order to bypass the congested event bus. With `--async`, the CLI tool will print the job id (jid) and exit immediately without listening for responses. You can then use `salt-run jobs.lookup_jid` to look up the results of the job in the job cache later.
```

Mutliple proxy tests are failing. https://jenkins.saltstack.com/job/branch_tests/job/Proxy/view/Python3/job/develop_ubuntu16_py3/255/

ping @gtmanfred mind taking a look here?

**Comment by Ch3LL** [comment]
And we have success!!!:

https://jenkins.saltstack.com/job/Oxygen/view/Proxy/job/oxygen-salt-cent7-proxy-py3/15/console
