### ISSUE TITLE
[oxygen] centos7 does not finish test run due to memory error

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#588]
The tests on centos7 are not completing due to a memory allocation error:

https://jenkins.saltstack.com/job/Oxygen/job/oxygen-salt-cent7-py2/5/consoleFull#-16628106710e76b7d7-9f01-494c-85a3-3ee3e5ff3147

```
03:56:49    -> unit.config.test_config.ConfigTestCase.test_sha256_is_default_for_minion  
03:56:49        Traceback (most recent call last):
03:56:49          File "/testing/tests/unit/config/test_config.py", line 102, in test_sha256_is_default_for_minion
03:56:49            config = sconfig.minion_config(fpath)
03:56:49          File "/testing/salt/config/__init__.py", line 2362, in minion_config
03:56:49            minion_id=minion_id)
03:56:49          File "/testing/salt/config/__init__.py", line 3690, in apply_minion_config
03:56:49            cache_minion_id=cache_minion_id)
03:56:49          File "/testing/salt/config/__init__.py", line 3586, in get_id
03:56:49            newid = salt.utils.network.generate_minion_id()
03:56:49          File "/testing/salt/utils/network.py", line 171, in generate_minion_id
03:56:49            return _generate_minion_id().first() or 'localhost'
03:56:49          File "/testing/salt/utils/network.py", line 161, in _generate_minion_id
03:56:49            return hosts.extend([addr for addr in ip_addrs()
03:56:49          File "/testing/salt/utils/network.py", line 1197, in ip_addrs
03:56:49            return _ip_addrs(interface, include_loopback, interface_data, 'inet')
03:56:49          File "/testing/salt/utils/network.py", line 1172, in _ip_addrs
03:56:49            else interfaces()
03:56:49          File "/testing/salt/utils/network.py", line 962, in interfaces
03:56:49            return linux_interfaces()
03:56:49          File "/testing/salt/utils/network.py", line 840, in linux_interfaces
03:56:49            stderr=subprocess.STDOUT).communicate()[0]
03:56:49          File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
03:56:49            errread, errwrite)
03:56:49          File "/usr/lib64/python2.7/subprocess.py", line 1224, in _execute_child
03:56:49            self.pid = os.fork()
03:56:49        OSError: [Errno 12] Cannot allocate memory
03:56:49    .............................................................................
03:56:49  -------------------------------------------------------------------------------
03:56:49 ================================================================================
03:56:49 
FAILED (total=7969, skipped=639, passed=7293, failures=1, errors=36) 
03:56:49 ============================  Overall Tests Report  ============================
04:00:30 Connection to 45.33.109.142 closed.
04:00:31 --------------------------------------------------------------------------------
04:00:31  * Failed execute command. Exit code: 1
04:00:31 <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
04:00:31  * The execution of the test command [u'/usr/bin/python2', '//testing/tests/runtests.py', '-v', '--run-destructive', '--sysinfo', '--transport=zeromq', '--output-columns=80', '--ssh', '--coverage-xml=/tmp/coverage.xml', '--xml=/tmp/xml-unittests-output'] failed
```

**Comment by rallytime** [comment]
I am not seeing this anymore. I'll close this for now. We can reopen if there are issues again.

**Comment by gtmanfred** [comment]
:+1:
