### ISSUE TITLE
Failed test: unit.proxy.test_esxcluster.InitTestCase.test_invalid_proxy_input_error

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#620]
- unit.proxy.test_esxcluster.InitTestCase.test_invalid_proxy_input_error
```
Traceback (most recent call last):
  File "/testing/salt/proxy/esxcluster.py", line 210, in init
    jsonschema.validate(proxy_conf, schema)
  File "/usr/lib/python3.5/unittest/mock.py", line 917, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/lib/python3.5/unittest/mock.py", line 973, in _mock_call
    raise effect
jsonschema.exceptions.ValidationError: Validation Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/testing/tests/unit/proxy/test_esxcluster.py", line 94, in test_invalid_proxy_input_error
    esxcluster.init(self.opts_userpass)
  File "/testing/salt/proxy/esxcluster.py", line 212, in init
    raise salt.exceptions.InvalidConfigError(exc)
  File "/testing/salt/exceptions.py", line 159, in __init__
    super(CommandExecutionError, self).__init__(exc_str)
  File "/testing/salt/exceptions.py", line 46, in __init__
    salt.utils.stringutils.to_str(message)
  File "/testing/salt/utils/stringutils.py", line 57, in to_str
    raise TypeError('expected str, bytes, or bytearray not {}'.format(type(s)))
TypeError: expected str, bytes, or bytearray not <class 'jsonschema.exceptions.ValidationError'>
```

Probably related to the failure in #616.

**Comment by rallytime** [comment]
Duplicate of #618. Closing.
