### ISSUE TITLE
Test Failed: unit.modules.test_btrfs.BtrfsTestCase.test_properties_error

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#621]
- unit.modules.test_btrfs.BtrfsTestCase.test_properties_error
```
Traceback (most recent call last):
  File "/testing/salt/modules/btrfs.py", line 661, in properties
    for keyset in set.split(",")]:
AttributeError: 'bool' object has no attribute 'split'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/testing/tests/unit/modules/test_btrfs.py", line 364, in test_properties_error
    '/dev/sda1', 'subvol', True)
  File "/usr/lib/python3.5/unittest/case.py", line 727, in assertRaises
    return context.handle('assertRaises', args, kwargs)
  File "/usr/lib/python3.5/unittest/case.py", line 176, in handle
    callable_obj(*args, **kwargs)
  File "/testing/salt/modules/btrfs.py", line 665, in properties
    raise CommandExecutionError(ex)
  File "/testing/salt/exceptions.py", line 159, in __init__
    super(CommandExecutionError, self).__init__(exc_str)
  File "/testing/salt/exceptions.py", line 46, in __init__
    salt.utils.stringutils.to_str(message)
  File "/testing/salt/utils/stringutils.py", line 57, in to_str
    raise TypeError('expected str, bytes, or bytearray not {}'.format(type(s)))
TypeError: expected str, bytes, or bytearray not <class 'AttributeError'>	
```

**Comment by rallytime** [comment]
This looks like it was fixed with https://github.com/saltstack/salt/pull/45038
