### ISSUE TITLE
~25 tests failing in unit.modules.test_dockermod in Python 3

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#622]
These tests are all failing with a similar message:
```
Traceback (most recent call last):
  File "/testing/tests/unit/modules/test_dockermod.py", line 329, in test_list_volumes
    filters={'dangling': [True]},
  File "/testing/salt/modules/dockermod.py", line 5453, in volumes
    response = _client_wrapper('volumes', filters=filters)
  File "/testing/salt/modules/dockermod.py", line 409, in wrapper
    kwargs = __utils__['args.clean_kwargs'](**kwargs)
  File "/testing/salt/loader.py", line 1138, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/testing/salt/utils/lazy.py", line 99, in __getitem__
    if self._load(key):
  File "/testing/salt/loader.py", line 1603, in _load
    raise KeyError
KeyError
```

**Comment by rallytime** [comment]
This should be fixed with https://github.com/saltstack/salt/pull/45095

**Comment by rallytime** [comment]
This is fixed now.
