### ISSUE TITLE
Failed test: integration.netapi.rest_cherrypy.test_app.TestJobs.test_all_jobs

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#623]
- integration.netapi.rest_cherrypy.test_app.TestJobs.test_all_jobs
```
Traceback (most recent call last):
  File "/testing/tests/integration/netapi/rest_cherrypy/test_app.py", line 257, in test_all_jobs
    self.assertIn('test.ping', str(resp['return']))
AssertionError: 'test.ping' not found in '[\'Exception occurred in runner jobs.list_jobs: Traceback (most recent call last):\\n  File "/testing/salt/client/mixins.py", line 387, in _low\\n    data[\\\'return\\\'] = self.functions[fun](*args, **kwargs)\\n  File "/testing/salt/runners/jobs.py", line 306, in list_jobs\\n    ret = mminion.returners[\\\'{0}.get_jids\\\'.format(returner)]()\\n  File "/testing/salt/returners/local_cache.py", line 361, in get_jids\\n    for jid, job, _, _ in _walk_through(_job_dir()):\\n  File "/testing/salt/returners/local_cache.py", line 75, in _walk_through\\n    job = serial.load(rfh)\\n  File "/testing/salt/payload.py", line 164, in load\\n    return self.loads(data, encoding=\\\'utf-8\\\')\\n  File "/testing/salt/payload.py", line 137, in loads\\n    ret = msgpack.loads(msg, use_list=True, encoding=encoding)\\n  File "/usr/local/lib/python3.5/dist-packages/msgpack/fallback.py", line 100, in unpackb\\n    raise ExtraData(ret, unpacker._fb_get_extradata())\\nmsgpack.exceptions.ExtraData: unpack(b) received extra data.\\n\']'
```
This is for python 3

**Comment by rallytime** [comment]
This looks to be fixed by https://github.com/saltstack/salt/pull/45038
