### ISSUE TITLE
[oxygen][salt-cloud] GCE Failing on creationg of VM

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#626]
When running the test suite it is not creating the VM.

```
11:28:37 Traceback (most recent call last):
11:28:37   File "/testing/tests/integration/cloud/providers/test_gce.py", line 86, in test_instance
11:28:37     self.assertIn(ret_str, instance)
11:28:37 AssertionError: 'CLOUD-TEST-OLIMKL:' not found in []
```

Finally tracked it down to a regex check that I don't believe currently allows a capitilized latter in the VM name when creating a VM. Going to try to track down a fix.

**Comment by Ch3LL** [comment]
update: found it was changed in this commit: https://github.com/saltstack/salt/pull/42035/commits/80f53cd98cc1bd2d68e3582592789ce890fb088c

As you can see we were previously using a lowercase name for the VM for gce tests. Need to find out if this is on purpose or if we need to update the regex.

**Comment by Ch3LL** [comment]
Okay looks like it is a requirement of GCE to be a lowercase name. When removing the regex check in salt-cloud gce.py file I received this error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/gce.py", line 2518, in request_instance
    node_data = conn.create_node(**kwargs)
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 3883, in create_node
    self.connection.async_request(request, method='POST', data=node_data)
  File "/usr/lib/python2.7/site-packages/libcloud/common/base.py", line 772, in async_request
    response = request(**kwargs)
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 121, in request
    response = super(GCEConnection, self).request(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/libcloud/common/google.py", line 808, in request
    *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/libcloud/common/base.py", line 637, in request
    response = responseCls(**kwargs)
  File "/usr/lib/python2.7/site-packages/libcloud/common/base.py", line 159, in __init__
    self.object = self.parse_body()
  File "/usr/lib/python2.7/site-packages/libcloud/common/google.py", line 288, in parse_body
    raise InvalidRequestError(message, self.status, code)
InvalidRequestError: {u'domain': u'global', u'message': u"Invalid value for field 'resource.name': 'CLOUD-TEST-JXKWRK'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)'", u'reason': u'invalid'}
```

so easy fix just need to change the name of the VM.

**Comment by rallytime** [comment]
Looks like this should be fixed now.
