### ISSUE TITLE
[oxygen][salt-cloud] Joyent VM Failure on Creation of VM

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#628]
Seeing this stack trace when trying to create a VM with our cloud tests:

```
[ERROR   ] There was a profile error: string indices must be integers, not str                                                     
Traceback (most recent call last):                               
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 284, in run                                                      
    self.config.get('names')    
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1448, in run_profile                                        
    ret[name] = self.create(vm_)                                 
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1278, in create                                             
    output = self.clouds[func](vm_)                              
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/joyent.py", line 279, in create                                         
    'image': get_image(vm_),    
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/joyent.py", line 137, in get_image                                      
    images = avail_images()     
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/joyent.py", line 851, in avail_images                                   
    ret[image['name']] = image  
TypeError: string indices must be integers, not str
```

**Comment by rallytime** [comment]
@Ch3LL Is this still failing?

**Comment by Ch3LL** [comment]
nope
