### ISSUE TITLE
[oxygen] MacOSX 10.11 py3 test_valid_docs failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#645]
The test integration.modules.test_sysmod.SysModuleTest.test_valid_docs is failing on MacOSX 10.11 py3 tests with error:

```
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/integration/modules/test_sysmod.py", line 25, in test_valid_docs
    '\n'.join(['  - {0}'.format(f) for f in ret['missing_docstring']]),
TypeError: 'bool' object is not subscriptable
```

http://mac-jenkins:8080/job/oxygen/job/macOS-py3-10.11/3/testReport/junit/integration.modules.test_sysmod/SysModuleTest/test_valid_docs/

**Comment by Ch3LL** [comment]
can't replicate. re-running tests.

**Comment by Ch3LL** [comment]
seeing this stack trace when re-running tests in jenkins: 

```
14:48:27 Process salt.utils.ssdp.<class 'method'>.run:
14:48:27 Traceback (most recent call last):
14:48:27   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
14:48:27     self.run()
14:48:27   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
14:48:27     self._target(*self._args, **self._kwargs)
14:48:27   File "/testing/salt/utils/ssdp.py", line 312, in run
14:48:27     loop.create_datagram_endpoint(protocol, local_addr=(listen_ip, port), allow_broadcast=True))
14:48:27   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
14:48:27     return future.result()
14:48:27   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 933, in create_datagram_endpoint
14:48:27     raise exceptions[0]
14:48:27   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 918, in create_datagram_endpoint
14:48:27     sock.bind(local_address)
14:48:27 OSError: [Errno 48] Address already in use
``` 

and doesn't look like any of the tests are running. my initial suspicions are related to the new discovery stuff added in oxygen. I'm guessing whichever PR we add for this issue: https://github.com/saltstack/salt/issues/45056  will resolve the issue as we will be disabling discovery by default.

Looking to see if i can replicate it when running the entire test suite locally, then will check what happens when disabling discovery by default.

**Comment by Ch3LL** [comment]
this error is not occuring anymore. Also the initial test in this issue failed again. so need to dive in more.
