### ISSUE TITLE
[oxygen] salt-cloud tests: vmware failures

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#649]
The following vmware tests are failing on both py2 and py3:

```
15:05:45    -> integration.cloud.providers.test_vmware.VMWareTest.test_instance  ........
15:05:45        Traceback (most recent call last):
15:05:45          File "/testing/tests/integration/cloud/providers/test_vmware.py", line 96, in test_instance
15:05:45            self.assertIn(ret_str, instance)
15:05:45        AssertionError: 'CLOUD-TEST-EMKGAF:' not found in []
15:05:45    .............................................................................
15:05:45    -> integration.cloud.providers.test_vmware.VMWareTest.test_snapshot  ........
15:05:45        Traceback (most recent call last):
15:05:45          File "/testing/tests/integration/cloud/providers/test_vmware.py", line 121, in test_snapshot
15:05:45            self.assertIn(ret_str, instance)
15:05:45        AssertionError: 'CLOUD-TEST-EMKGAF:' not found in []
15:05:45    .............................................................................
```

**Comment by gtmanfred** [comment]
These appear to be passing now.
