### ISSUE TITLE
[oxygen] salt-cloud: ec2 failures

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#650]
The following salt-cloud ec2 tests are failing on py2 and py3:

```
15:05:45    -> integration.cloud.providers.test_ec2.EC2Test.test_instance  ..............
15:05:45        Traceback (most recent call last):
15:05:45          File "/testing/tests/integration/cloud/providers/test_ec2.py", line 89, in test_instance
15:05:45            self.assertIn(ret_str, instance)
15:05:45        AssertionError: 'CLOUD-TEST-1WFBO7:' not found in []
15:05:45    .............................................................................
15:05:45    -> integration.cloud.providers.test_ec2.EC2Test.test_instance_rename  .......
15:05:45        Traceback (most recent call last):
15:05:45          File "/testing/tests/integration/cloud/providers/test_ec2.py", line 115, in test_instance_rename
15:05:45            self.assertIn(ret_str, instance)
15:05:45        AssertionError: 'CLOUD-TEST-1WFBO7:' not found in []
```

**Comment by garethgreenaway** [comment]
AWS access credentials had been set to inactive.

**Comment by rallytime** [comment]
This should be fixed now.
