### ISSUE TITLE
[2017.7] PY3: unittest.loader.ModuleImportFailure.unit.grains.test_core failure

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#676]
```
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.4/unittest/case.py", line 577, in run
    testMethod()
  File "/usr/lib/python3.4/unittest/loader.py", line 32, in testFailure
    raise exception
ImportError: Failed to import test module: unit.grains.test_core
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/loader.py", line 312, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.4/unittest/loader.py", line 290, in _get_module_from_name
    __import__(name)
  File "/testing/tests/unit/grains/test_core.py", line 32, in <module>
    IPv4Address = salt.ext.ipaddress.IPv4Address
AttributeError: 'module' object has no attribute 'ipaddress'
```

I have seen this fail frequently on PR tests, but I am not sure if it's consistent or not. Currently I am looking at this build on Debian 8 Python 3: https://jenkins.saltstack.com/job/2017.7/view/Branch%20Python%203/job/salt-linode-py3-debian8/lastCompletedBuild/testReport/unittest.loader.ModuleImportFailure.unit/grains/test_core/

As well as Py3 Fedora 27: https://jenkins.saltstack.com/job/2017.7/view/Branch%20Python%203/job/2017.7-salt-fedora27-py3/lastCompletedBuild/testReport/

Py3 Ubuntu 16: https://jenkins.saltstack.com/job/2017.7/view/Branch%20Python%203/job/salt-lin-py3-ubuntu16/lastCompletedBuild/testReport/

Py3 Ubuntu 17: https://jenkins.saltstack.com/job/2017.7/view/Branch%20Python%203/job/salt-linode-py3-ubuntu17/lastCompletedBuild/testReport/

**Comment by rallytime** [comment]
@gtmanfred Good news - Erik fixed this one in https://github.com/saltstack/salt/pull/45388
