### ISSUE TITLE
[2017.7] salt-cloud vmware tests failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#694]
On 2017.7 branch tests vmware test is failing:

```
16:17:37  --------  Failed Tests  -------------------------------------------------------
16:17:37    -> integration.cloud.providers.test_vmware.VMWareTest.test_instance  ........
16:17:37        Traceback (most recent call last):
16:17:37          File "/testing/tests/integration/cloud/providers/test_vmware.py", line 109, in test_instance
16:17:37            self.assertIn(ret_str, instance)
16:17:37        AssertionError: 'CLOUD-TEST-OAQBLH:' not found in []
16:17:37    .............................................................................
16:17:37    -> integration.cloud.providers.test_vmware.VMWareTest.test_snapshot  ........
16:17:37        Traceback (most recent call last):
16:17:37          File "/testing/tests/integration/cloud/providers/test_vmware.py", line 134, in test_snapshot
16:17:37            self.assertIn(ret_str, instance)
16:17:37        AssertionError: 'CLOUD-TEST-OAQBLH:' not found in []
16:17:37    .............................................................................
```

**Comment by rallytime** [comment]
@Ch3LL Is this still failing?

**Comment by Ch3LL** [comment]
nope
