### ISSUE TITLE
[2017.7.3] Ubuntu 16 not bootstrapping on Py3 tests

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#712]
```
12:29:36  * Running command: salt-cloud -l info --script-args="-ZD -P git v2016.11.3" -p linode_ubuntu16_8192 Zjk-2017_7_3-lin-py3-ubuntu16-3
12:29:36 --------------------------------------------------------------------------------
12:29:37 [INFO    ] salt-cloud starting
12:29:41 [INFO    ] Creating Cloud VM Zjk-2017_7_3-lin-py3-ubuntu16-3
12:29:49 [INFO    ] Status for Linode 5264232 is 'Being Created', waiting for 'Brand New'.
12:29:54 [INFO    ] Status for Linode 5264232 is 'Being Created', waiting for 'Brand New'.
12:30:23 [ERROR   ] Failed to create VM Zjk-2017_7_3-lin-py3-ubuntu16-3. Configuration value 0 needs to be set
12:30:23 Traceback (most recent call last):
12:30:23   File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1288, in create
12:30:23     output = self.clouds[func](vm_)
12:30:23   File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/linode.py", line 504, in create
12:30:23     'check_running': False})
12:30:23   File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/linode.py", line 271, in boot
12:30:23     if not _wait_for_job(linode_id, boot_job_id):
12:30:23   File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/linode.py", line 1550, in _wait_for_job
12:30:23     if jobs_result[0]['JOBID'] == job_id and jobs_result[0]['HOST_SUCCESS'] == 1:
12:30:23 KeyError: 0
12:30:23 
Error: There was a profile error: Failed to deploy VM
```

https://jenkins.saltstack.com/job/2017.7.3/view/Branch%20Python%203/job/salt-lin-py3-ubuntu16/lastFailedBuild/console

**Comment by dubb-b** [comment]
@rallytime The profile was updated and the tests are running.
https://jenkins.saltstack.com/job/2017.7.3/view/Branch%20Python%203/job/salt-lin-py3-ubuntu16/4/console
