### ISSUE TITLE
[oxygen] Ubuntu 14 failing shell integration test

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#785]
- integration.shell.test_call.CallTest.test_issue_15074_output_file_append 
```
Traceback (most recent call last):
  File "/testing/tests/integration/shell/test_call.py", line 346, in test_issue_15074_output_file_append
    with salt.utils.files.fopen(output_file_append) as ofa:
  File "/testing/salt/utils/files.py", line 366, in fopen
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
IOError: [Errno 2] No such file or directory: '/tmp/salt-tests-tmpdir/issue-15074'
```
https://jenkins.saltstack.com/job/Oxygen/job/oxygen-salt-ubuntu14.04-py2/lastCompletedBuild/testReport/

**Comment by terminalmage** [comment]
Can't reproduce this one, neither in docker nor in ec2.

**Comment by rallytime** [comment]
Looks like this isn't failing anymore. Closing.
