### ISSUE TITLE
[2017.7] Fedora 26 PY2 is failing on git.salt run

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#802]
```
14:41:43 ----------
14:41:43           ID: junos-eznc
14:41:43     Function: pip.installed
14:41:43       Result: False
14:41:43      Comment: Failed to install packages: junos-eznc. Error: Collecting junos-eznc
14:41:43                 Downloading https://nexus.c7.saltstack.net/repository/salt-proxy/packages/c2/56/5edfca17d8686a065ebd58e4ca6d03fb222dc02d70d589eed07f67bfa121/junos_eznc-2.1.7-py2.py3-none-any.whl (150kB)
14:41:43               Collecting scp>=0.7.0 (from junos-eznc)
14:41:43                 Downloading https://nexus.c7.saltstack.net/repository/salt-proxy/packages/f0/a3/bbb4a86cca67fd9db8527caae4221dc14e1900f81cc9caff1ac4724ea838/scp-0.10.2-py2.py3-none-any.whl
14:41:43               Requirement already satisfied: PyYAML>=3.10 in /usr/lib64/python2.7/site-packages (from junos-eznc)
14:41:43               Collecting lxml>=3.2.4 (from junos-eznc)
14:41:43                 Downloading https://nexus.c7.saltstack.net/repository/salt-proxy/packages/48/0b/94e83011d9b9b05a6edc8d0c424f6d2719b2bfc3cbf293ebea16c2ac3b30/lxml-4.1.1-cp27-cp27mu-manylinux1_x86_64.whl (5.6MB)
14:41:43               Collecting netaddr (from junos-eznc)
14:41:43                 Downloading https://nexus.c7.saltstack.net/repository/salt-proxy/packages/ba/97/ce14451a9fd7bdb5a397abf99b24a1a6bb7a1a440b019bebd2e9a0dbec74/netaddr-0.7.19-py2.py3-none-any.whl (1.6MB)
14:41:43               Collecting pyserial (from junos-eznc)
14:41:43                 Downloading https://nexus.c7.saltstack.net/repository/salt-proxy/packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl (193kB)
14:41:43               Collecting ncclient>=0.5.3 (from junos-eznc)
14:41:44                 Downloading https://nexus.c7.saltstack.net/repository/salt-proxy/packages/e9/cf/cb131bcaf9b31f8d9d1b9ec3aa9a861dd72a7269a9ff07217b60157fa526/ncclient-0.5.3.tar.gz (63kB)
14:41:44               Requirement already satisfied: jinja2>=2.7.1 in /usr/lib/python2.7/site-packages (from junos-eznc)
14:41:44               Requirement already satisfied: six in /usr/lib/python2.7/site-packages (from junos-eznc)
14:41:44               Collecting paramiko>=1.15.2 (from junos-eznc) WARNING: Running pip install with root privileges is generally not a good idea. Try `pip2 install --user` instead.
14:41:44                 Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9e01985890>: Failed to establish a new connection: [Errno 111] Connection refused',)': /repository/salt-proxy/packages/be/9f/2b899b028aec1f3973253c0cf8dda6fbff65f4930f7ebedc43033e9f1b18/paramiko-2.4.0-py2.py3-none-any.whl
14:41:44                 Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9e019850d0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /repository/salt-proxy/packages/be/9f/2b899b028aec1f3973253c0cf8dda6fbff65f4930f7ebedc43033e9f1b18/paramiko-2.4.0-py2.py3-none-any.whl
14:41:44                 Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9e00a04290>: Failed to establish a new connection: [Errno 111] Connection refused',)': /repository/salt-proxy/packages/be/9f/2b899b028aec1f3973253c0cf8dda6fbff65f4930f7ebedc43033e9f1b18/paramiko-2.4.0-py2.py3-none-any.whl
14:41:44                 Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9e00a04990>: Failed to establish a new connection: [Errno 111] Connection refused',)': /repository/salt-proxy/packages/be/9f/2b899b028aec1f3973253c0cf8dda6fbff65f4930f7ebedc43033e9f1b18/paramiko-2.4.0-py2.py3-none-any.whl
14:41:44                 Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9e00a04050>: Failed to establish a new connection: [Errno 111] Connection refused',)': /repository/salt-proxy/packages/be/9f/2b899b028aec1f3973253c0cf8dda6fbff65f4930f7ebedc43033e9f1b18/paramiko-2.4.0-py2.py3-none-any.whl
14:41:44               Exception:
14:41:44               Traceback (most recent call last):
14:41:44                 File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
14:41:44                   status = self.run(options, args)
14:41:44                 File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 357, in run
14:41:44                   wb.build(autobuilding=True)
14:41:44                 File "/usr/lib/python2.7/site-packages/pip/wheel.py", line 753, in build
14:41:44                   self.requirement_set.prepare_files(self.finder)
14:41:44                 File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
14:41:44                   ignore_dependencies=self.ignore_dependencies))
14:41:44                 File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 620, in _prepare_file
14:41:44                   session=self.session, hashes=hashes)
14:41:44                 File "/usr/lib/python2.7/site-packages/pip/download.py", line 821, in unpack_url
14:41:44                   hashes=hashes
14:41:44                 File "/usr/lib/python2.7/site-packages/pip/download.py", line 659, in unpack_http_url
14:41:44                   hashes)
14:41:44                 File "/usr/lib/python2.7/site-packages/pip/download.py", line 853, in _download_http_url
14:41:44                   stream=True,
14:41:44                 File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
14:41:44                   return self.request('GET', url, **kwargs)
14:41:44                 File "/usr/lib/python2.7/site-packages/pip/download.py", line 386, in request
14:41:44                   return super(PipSession, self).request(method, url, *args, **kwargs)
14:41:44                 File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
14:41:44                   resp = self.send(prep, **send_kwargs)
14:41:44                 File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
14:41:44                   r = adapter.send(request, **kwargs)
14:41:44                 File "/usr/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
14:41:44                   resp = super(CacheControlAdapter, self).send(request, **kw)
14:41:44                 File "/usr/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 479, in send
14:41:44                   raise ConnectTimeout(e, request=request)
14:41:44               ConnectTimeout: HTTPSConnectionPool(host='nexus.c7.saltstack.net', port=443): Max retries exceeded with url: /repository/salt-proxy/packages/be/9f/2b899b028aec1f3973253c0cf8dda6fbff65f4930f7ebedc43033e9f1b18/paramiko-2.4.0-py2.py3-none-any.whl (Caused by ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f9e00a044d0>, 'Connection to nexus.c7.saltstack.net timed out. (connect timeout=15)'))
14:41:44      Started: 14:38:56.448678
14:41:44     Duration: 60456.685 ms
14:41:44      Changes:   
```
https://jenkins.saltstack.com/job/2017.7/job/salt-linode-fedora26/lastFailedBuild/console

**Comment by gtmanfred** [comment]
The next runs on each passed, looks like a blip on nexus

**Comment by gtmanfred** [comment]
Waiting for https://jenkins.saltstack.com/job/2017.7/job/salt-linode-fedora26/293/console before closing
