### ISSUE TITLE
[oxygen] Fedora 26 PY3 failing git.salt state run

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#803]
The following state is failing:
```
14:44:29 ----------
14:44:29           ID: cffi
14:44:29     Function: pip.installed
14:44:29         Name: cffi==1.11.0
14:44:29       Result: False
14:44:29      Comment: Failed to install packages: cffi==1.11.0. Error: Collecting cffi==1.11.0   Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fed8a077860>: Failed to establish a new connection: [Errno 111] Connection refused',)': /packages/bd/28/7129e4c0bd7f3c19e823654a4463410b439f468b96adfabfa9eedfcdc49a/cffi-1.11.0-cp36-cp36m-manylinux1_x86_64.whl
14:44:29                 Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fed8a077da0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /packages/bd/28/7129e4c0bd7f3c19e823654a4463410b439f468b96adfabfa9eedfcdc49a/cffi-1.11.0-cp36-cp36m-manylinux1_x86_64.whl
14:44:29                 Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fed894f6cc0>: Failed to establish a new connection: [Errno 111] Connection refused',)': /packages/bd/28/7129e4c0bd7f3c19e823654a4463410b439f468b96adfabfa9eedfcdc49a/cffi-1.11.0-cp36-cp36m-manylinux1_x86_64.whl
14:44:29                 Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fed8947e240>: Failed to establish a new connection: [Errno 111] Connection refused',)': /packages/bd/28/7129e4c0bd7f3c19e823654a4463410b439f468b96adfabfa9eedfcdc49a/cffi-1.11.0-cp36-cp36m-manylinux1_x86_64.whl
14:44:29                 Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fed894844a8>, 'Connection to pypi.c7.saltstack.net timed out. (connect timeout=15)')': /packages/bd/28/7129e4c0bd7f3c19e823654a4463410b439f468b96adfabfa9eedfcdc49a/cffi-1.11.0-cp36-cp36m-manylinux1_x86_64.whl
14:44:29               Exception:
14:44:29               Traceback (most recent call last):
14:44:29                 File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connection.py", line 142, in _new_conn
14:44:29                   (self.host, self.port), self.timeout, **extra_kw)
14:44:29                 File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/util/connection.py", line 98, in create_connection
14:44:29                   raise err
14:44:29                 File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/util/connection.py", line 88, in create_connection
14:44:29                   sock.connect(sa)
14:44:29               socket.timeout: timed out
14:44:29               
14:44:29               During handling of the above exception, another exception occurred:
14:44:29               
14:44:29               Traceback (most recent call last):
14:44:29                 File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
14:44:29                   chunked=chunked)
14:44:29                 File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
14:44:29                   self._validate_conn(conn)
14:44:29                 File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
14:44:29                   conn.connect()
14:44:29                 File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connection.py", line 254, in connect
14:44:29                   conn = self._new_conn()
14:44:29                 File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connection.py", line 147, in _new_conn
14:44:29                   (self.host, self.timeout))
14:44:29               pip._vendor.requests.packages.urllib3.exceptions.ConnectTimeoutError: (<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fed8948b080>, 'Connection to pypi.c7.saltstack.net timed out. (connect timeout=15)')
14:44:29               
14:44:29               During handling of the above exception, another exception occurred:
14:44:29               
14:44:29               Traceback (most recent call last):
14:44:29                 File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 423, in send
14:44:29                   timeout=timeout
14:44:29                 File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
14:44:30                   release_conn=release_conn, **response_kw)
14:44:30                 File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
14:44:30                   release_conn=release_conn, **response_kw)
14:44:30                 File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
14:44:30                   release_conn=release_conn, **response_kw)
14:44:30                 [Previous line repeated 1 more times]
14:44:30                 File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
14:44:30                   _stacktrace=sys.exc_info()[2])
14:44:30                 File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/util/retry.py", line 287, in increment
14:44:30                   raise MaxRetryError(_pool, url, error or ResponseError(cause))
14:44:30               pip._vendor.requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pypi.c7.saltstack.net', port=443): Max retries exceeded with url: /packages/bd/28/7129e4c0bd7f3c19e823654a4463410b439f468b96adfabfa9eedfcdc49a/cffi-1.11.0-cp36-cp36m-manylinux1_x86_64.whl (Caused by ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fed8948b080>, 'Connection to pypi.c7.saltstack.net timed out. (connect timeout=15)'))
14:44:30               
14:44:30               During handling of the above exception, another exception occurred:
14:44:30               
14:44:30               Traceback (most recent call last):
14:44:30                 File "/usr/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
14:44:30                   status = self.run(options, args)
14:44:30                 File "/usr/lib/python3.6/site-packages/pip/commands/install.py", line 335, in run
14:44:30                   wb.build(autobuilding=True)
14:44:30                 File "/usr/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
14:44:30                   self.requirement_set.prepare_files(self.finder)
14:44:30                 File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
14:44:30                   ignore_dependencies=self.ignore_dependencies))
14:44:30                 File "/usr/lib/python3.6/site-packages/pip/req/req_set.py", line 620, in _prepare_file
14:44:30                   session=self.session, hashes=hashes)
14:44:30                 File "/usr/lib/python3.6/site-packages/pip/download.py", line 821, in unpack_url
14:44:30                   hashes=hashes
14:44:30                 File "/usr/lib/python3.6/site-packages/pip/download.py", line 659, in unpack_http_url
14:44:30                   hashes)
14:44:30                 File "/usr/lib/python3.6/site-packages/pip/download.py", line 853, in _download_http_url
14:44:30                   stream=True,
14:44:30                 File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
14:44:30                   return self.request('GET', url, **kwargs)
14:44:30                 File "/usr/lib/python3.6/site-packages/pip/download.py", line 386, in request
14:44:30                   return super(PipSession, self).request(method, url, *args, **kwargs)
14:44:30                 File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
14:44:30                   resp = self.send(prep, **send_kwargs)
14:44:30                 File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
14:44:30                   r = adapter.send(request, **kwargs)
14:44:30                 File "/usr/lib/python3.6/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
14:44:30                   resp = super(CacheControlAdapter, self).send(request, **kw)
14:44:30                 File "/usr/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 479, in send
14:44:30                   raise ConnectTimeout(e, request=request)
14:44:30               pip._vendor.requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='pypi.c7.saltstack.net', port=443): Max retries exceeded with url: /packages/bd/28/7129e4c0bd7f3c19e823654a4463410b439f468b96adfabfa9eedfcdc49a/cffi-1.11.0-cp36-cp36m-manylinux1_x86_64.whl (Caused by ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fed8948b080>, 'Connection to pypi.c7.saltstack.net timed out. (connect timeout=15)'))
14:44:30      Started: 14:39:29.021789
14:44:30     Duration: 45622.672 ms
14:44:30      Changes:   
```
https://jenkins.saltstack.com/job/Oxygen/view/Branch%20Python%203/job/oxygen-salt-fedora26-py3/lastFailedBuild/consoleFull

**Comment by gtmanfred** [comment]
The next runs on each passed, looks like a blip on nexus
