### ISSUE TITLE
[oxygen.rc1] Debian 9 PY3 has 1 pkg integration test failure

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#819]
- integration.modules.test_pkg.PkgModuleTest.test_install_remove
```
Traceback (most recent call last):
  File "/testing/tests/support/helpers.py", line 580, in wrapper
    return func(cls)
  File "/testing/tests/support/helpers.py", line 88, in wrap
    return caller(cls)
  File "/testing/tests/integration/modules/test_pkg.py", line 162, in test_install_remove
    test_install()
  File "/testing/tests/integration/modules/test_pkg.py", line 149, in test_install
    self.assertIn(self.pkg, install_ret)
AssertionError: 'htop' not found in 'ERROR: Problem encountered installing package(s). Additional info follows:\n\nchanges:\n    ----------\nerrors:\n    - Running scope as unit: run-r1944b5a756224195af3a2f8344729191.scope\n      E: Held packages were changed and -y was used without --allow-change-held-packages.'
```
https://jenkins.saltstack.com/job/oxygen.rc1/view/Branch%20Python%203/job/oxygen-salt-debian9-py3/lastCompletedBuild/testReport/integration.modules.test_pkg/PkgModuleTest/test_install_remove/

**Comment by terminalmage** [comment]
I can't reproduce this locally, and I don't think it's a bug to be honest. This runs right after `test_hold_unhold`, so it's possible that apt is operating on outdated information? Let's keep an eye on this and see how reliably it fails.
