### ISSUE TITLE
[oxygen.rc1] CentOS 7 2 test_call integration shell test failures

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#820]
- integration.shell.test_call.CallTest.test_issue_14979_output_file_permissions
```
Traceback (most recent call last):
  File "/testing/tests/integration/shell/test_call.py", line 378, in test_issue_14979_output_file_permissions
    stat1 = os.stat(output_file)
OSError: [Errno 2] No such file or directory: '/tmp/salt-tests-tmpdir/issue-14979'
```
- integration.shell.test_call.CallTest.test_issue_15074_output_file_append
```
Traceback (most recent call last):
  File "/testing/tests/integration/shell/test_call.py", line 346, in test_issue_15074_output_file_append
    with salt.utils.files.fopen(output_file_append) as ofa:
  File "/testing/salt/utils/files.py", line 366, in fopen
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
IOError: [Errno 2] No such file or directory: '/tmp/salt-tests-tmpdir/issue-15074'
```
https://jenkins.saltstack.com/job/oxygen.rc1/job/oxygen-salt-cent7-py2/lastCompletedBuild/testReport/

**Comment by terminalmage** [comment]
These are happening because of timeouts.
