### ISSUE TITLE
[oxygen.rc1] Ubuntu 17 has 1 ssh state ingetration test failing

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#822]
- `integration.ssh.test_state.SSHStateTest.test_state_single`
```
Traceback (most recent call last):
  File "/testing/tests/integration/ssh/test_state.py", line 86, in test_state_single
    for key, value in six.iteritems(single):
  File "/testing/salt/ext/six.py", line 606, in iteritems
    return d.iteritems(**kw)
AttributeError: 'list' object has no attribute 'iteritems'
```
https://jenkins.saltstack.com/job/oxygen.rc1/job/oxygen-salt-ubuntu17.04-py2/lastCompletedBuild/testReport/

**Comment by terminalmage** [comment]
Can't reproduce this, and it's not failing on newer builds. Looking at the log from the last failed build, this appeared to have been from a timeout:

```
08:38:31,771 [tests.support.case                         :483 ][DEBUG   ] Result of run_ssh for command ' -W -ldebug -c /tmp/salt-tests-tmpdir/config -i --priv /tmp/salt-tests-tmpdir/config/key_test --roster-file /tmp/salt-tests-tmpdir/config/roster --out=json localhost state.single test.succeed_with_changes name=itworked': ['Process took more than 90 seconds to complete. Process Killed!']
08:38:31,771 [tests.support.case                         :845 ][DEBUG   ] SSHCase run_function executed state.single with arg [u'test.succeed_with_changes name=itworked']
08:38:31,771 [tests.support.case                         :846 ][DEBUG   ] SSHCase JSON return: ['Process took more than 90 seconds to complete. Process Killed!']
```
