### ISSUE TITLE
[develop] 1 Core grain unit test is failing

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#882]
- unit.grains.test_core.CoreGrainsTestCase.test_fqdns_return

```
Traceback (most recent call last):
  File "/testing/tests/unit/grains/test_core.py", line 931, in test_fqdns_return
    self._run_fqdns_test(reverse_resolv_mock, ret)
  File "/testing/tests/unit/grains/test_core.py", line 941, in _run_fqdns_test
    self.assertEqual(fqdns, ret)
AssertionError: {'fqdns': ['rinzler.evil-corp.com', 'bluesniff.foo.bar', 'foo.bar.baz']} != {'fqdns': ['rinzler.evil-corp.com', 'foo.bar.baz', 'bluesniff.foo.bar']}
- {'fqdns': ['rinzler.evil-corp.com', 'bluesniff.foo.bar', 'foo.bar.baz']}
?                                                        ---------------

+ {'fqdns': ['rinzler.evil-corp.com', 'foo.bar.baz', 'bluesniff.foo.bar']}
?                                     +++++++++++++++
```

This has been failing on develop for a while, I just didn't have time to file an issue for it yet. It is failing consistently on PRs (against develop) and the develop branch, so it should be easy to reproduce.

@garethgreenaway Can you take a look at this one?

**Comment by garethgreenaway** [comment]
@rallytime On it.

**Comment by rallytime** [comment]
@garethgreenaway You rock!
