### ISSUE TITLE
[2017.7.5] [Centos 6] unit.test_minion.MinionTestCase.test_sock_path_len

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt-jenkins#883]
Error Message

I/O operation on closed epoll fd

Stacktrace

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/test_minion.py", line 48, in test_sock_path_len
    event_publisher = event.AsyncEventPublisher(__opts__)
  File "/tmp/kitchen/testing/salt/utils/event.py", line 1019, in __init__
    self.publisher.start()
  File "/tmp/kitchen/testing/salt/transport/ipc.py", line 517, in start
    io_loop=self.io_loop,
  File "/usr/lib64/python2.7/site-packages/tornado/netutil.py", line 278, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 728, in add_handler
    self._impl.register(fd, events | self.ERROR)
ValueError: I/O operation on closed epoll fd

https://jenkinsci.saltstack.com/job/2017.7.5/job/salt-centos-6-py2/lastCompletedBuild/testReport/unit.test_minion/MinionTestCase/test_sock_path_len/

**Comment by gtmanfred** [comment]
I can only replicate this if I run all of the unit tests, if I just run one, it doesn't happen.

```
        --------  Tests with Errors  --------------------------------------------------
          -> unit.test_minion.MinionTestCase.test_sock_path_len  ......................
       Traceback (most recent call last):
         File "/tmp/kitchen/testing/tests/unit/test_minion.py", line 48, in test_sock_path_len
           event_publisher = event.AsyncEventPublisher(__opts__)
         File "/tmp/kitchen/testing/salt/utils/event.py", line 1019, in __init__
           self.publisher.start()
         File "/tmp/kitchen/testing/salt/transport/ipc.py", line 517, in start
           io_loop=self.io_loop,
         File "/usr/lib64/python2.7/site-packages/tornado/netutil.py", line 278, in add_accept_handler
           io_loop.add_handler(sock, accept_handler, IOLoop.READ)
         File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 728, in add_handler
verifier:
           self._impl.register(fd, events | self.ERROR)
       ValueError: I/O operation on closed epoll fd
```

**Comment by gtmanfred** [comment]
This is being caused by the new pyzmq 17.0.0 that is being installed on centos 6 because we haven't pinned it for centos 6 installs of 2017.7, and we install with -P in bootstrap.

**Comment by terminalmage** [comment]
@gtmanfred So is the correct fix to make the change in salt-jenkins, or to keep the flaky decorator that you added when we were testing.
