### ISSUE TITLE
[2017.7.5][Opensuse][py2] integration.modules.test_pkg.PkgModuleTest.test_pkg_upgrade_has_pending_upgrades

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt-jenkins#885]
```
Error Message

'vim' not found in {'kernel-default': {'new': '4.4.114-42.1', 'old': '4.4.104-39.1,4.4.114-42.1'}, 'gpg-pubkey': {'new': 'a0e46e11-5911fc35', 'old': '05f4861f-54c3f34e,29dd7d91-59c28934,307e3d54-4be01a65,3dbdc284-53674dd4,a0e46e11-5911fc35'}, 'crash-kmp-default': {'new': '7.1.8_k4.4.76_1-1.4', 'old': '7.1.8_k4.4.104_39-4.1,7.1.8_k4.4.76_1-1.4'}}

Stacktrace

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 574, in wrapper
    return func(cls)
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 87, in wrap
    return caller(cls)
  File "/tmp/kitchen/testing/tests/integration/modules/test_pkg.py", line 306, in test_pkg_upgrade_has_pending_upgrades
    self.assertIn('vim', ret)
AssertionError: 'vim' not found in {'kernel-default': {'new': '4.4.114-42.1', 'old': '4.4.104-39.1,4.4.114-42.1'}, 'gpg-pubkey': {'new': 'a0e46e11-5911fc35', 'old': '05f4861f-54c3f34e,29dd7d91-59c28934,307e3d54-4be01a65,3dbdc284-53674dd4,a0e46e11-5911fc35'}, 'crash-kmp-default': {'new': '7.1.8_k4.4.76_1-1.4', 'old': '7.1.8_k4.4.104_39-4.1,7.1.8_k4.4.76_1-1.4'}}
```
https://jenkinsci.saltstack.com/job/2017.7.5/job/salt-opensuse-py2/1/testReport/integration.modules.test_pkg/PkgModuleTest/test_pkg_upgrade_has_pending_upgrades/

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/46551
