### ISSUE TITLE
[2017.7.5][Fedora 26/Ubuntu 17.10][py3] integration.states.test_pip.PipStateTest.test_46127_pip_env_vars

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt-jenkins#886]
```
Error Message

True is not True. Salt Comment: Created new virtualenv

Stacktrace

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 546, in assertSaltTrueReturn
    self.assertTrue(saltret)
  File "/usr/lib64/python3.6/unittest/case.py", line 699, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/states/test_pip.py", line 562, in test_46127_pip_env_vars
    self.assertSaltTrueReturn(ret)
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 552, in assertSaltTrueReturn
    **(next(six.itervalues(ret)))
AssertionError: True is not True. Salt Comment:
Created new virtualenv
		
```
https://jenkinsci.saltstack.com/job/2017.7.5/view/Python3/job/salt-fedora-26-py3/1/testReport/integration.states.test_pip/PipStateTest/test_46127_pip_env_vars/
https://jenkinsci.saltstack.com/job/2017.7.5/view/Python3/job/salt-ubuntu-1710-py3/1/testReport/integration.states.test_pip/PipStateTest/test_46127_pip_env_vars/

**Comment by gtmanfred** [comment]
This is also failing on arch
https://jenkinsci.saltstack.com/job/2017.7.5/view/Python3/job/salt-arch-py3/lastCompletedBuild/testReport/
