### ISSUE TITLE
[2017.7.5] Mac 10.12 py2 integration.modules.test_pkg failure

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#891]
The test integration.modules.test_pkg.PkgModuleTest.test_pkg_upgrade_has_pending_upgrades is failing on mac 10.12 py2:

http://mac-jenkins:8080/job/2017.7.5/job/macOS-10.12/7/testReport/junit/integration.modules.test_pkg/PkgModuleTest/test_pkg_upgrade_has_pending_upgrades/

```
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/support/helpers.py", line 574, in wrapper
    return func(cls)
  File "/testing/tests/support/helpers.py", line 87, in wrap
    return caller(cls)
  File "/testing/tests/integration/modules/test_pkg.py", line 314, in test_pkg_upgrade_has_pending_upgrades
    if 'Problem encountered' in ret:
TypeError: argument of type 'bool' is not iterable
		
```

**Comment by Ch3LL** [comment]
I can confirm this is just the case of a problem with teh test VM. When running brew upgrade You can see a bunch of symlink failures:

openssl:

```
==> Upgrading openssl                                                                                                                                                                   
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2n.sierra.bottle.tar.gz                                                                                                
==> Pouring openssl-1.0.2n.sierra.bottle.tar.gz                                                                                                                                         
==> Caveats                                                                                                                                                                             
A CA file has been bootstrapped using certificates from the SystemRoots                                                                                                                 
keychain. To add additional certificates (e.g. the certificates added in                                                                                                                
the System keychain), place .pem files in                                                                                                                                               
  /usr/local/etc/openssl/certs                                                                                                                                                          
                                                                                                                                                                                        
and run                                                                                                                                                                                 
  /usr/local/opt/openssl/bin/c_rehash                                                                                                                                                   
                                                                                                                                                                                        
This formula is keg-only, which means it was not symlinked into /usr/local,                                                                                                             
because Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries.                                                                                               
                                                                                                                                                                                        
If you need to have this software first in your PATH run:                                                                                                                               
  echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> ~/.bash_profile                                                                                                              
                                                                                                                                                                                        
For compilers to find this software you may need to set:                                                                                                                                
    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include

==> Summary
<U+1F37A>  /usr/local/Cellar/openssl/1.0.2n: 1,792 files, 12.3MB
```

readline:

```
==> Upgrading readline
==> Downloading https://homebrew.bintray.com/bottles/readline-7.0.3_1.sierra.bottle.tar.gz
==> Pouring readline-7.0.3_1.sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS provides the BSD libedit library, which shadows libreadline.
In order to prevent conflicts when programs look for libreadline we are
defaulting this GNU Readline installation to keg-only..

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/readline/lib
    CPPFLAGS: -I/usr/local/opt/readline/include

==> Summary
<U+1F37A>  /usr/local/Cellar/readline/7.0.3_1: 46 files, 1.5MB
```

curl:

```
==> Upgrading curl
==> Downloading https://homebrew.bintray.com/bottles/curl-7.59.0.sierra.bottle.tar.gz
==> Pouring curl-7.59.0.sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/curl/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/curl/lib
    CPPFLAGS: -I/usr/local/opt/curl/include

==> Summary
<U+1F37A>  /usr/local/Cellar/curl/7.59.0: 421 files, 3MB
```

node:

```
==> Upgrading node
==> Installing dependencies for node: icu4c
==> Installing node dependency: icu4c
==> Downloading https://homebrew.bintray.com/bottles/icu4c-60.2.sierra.bottle.tar.gz
==> Pouring icu4c-60.2.sierra.bottle.tar.gz
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS provides libicucore.dylib (but nothing else).

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/icu4c/bin:$PATH"' >> ~/.bash_profile
  echo 'export PATH="/usr/local/opt/icu4c/sbin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/icu4c/lib
    CPPFLAGS: -I/usr/local/opt/icu4c/include

==> Summary
<U+1F37A>  /usr/local/Cellar/icu4c/60.2: 249 files, 67MB
```

```
==> Installing node
==> Downloading https://homebrew.bintray.com/bottles/node-9.8.0.sierra.bottle.tar.gz
==> Pouring node-9.8.0.sierra.bottle.tar.gz
The formula built, but is not symlinked into /usr/local
Could not symlink bin/node
Target /usr/local/bin/node
already exists. You may want to remove it:
  rm '/usr/local/bin/node'

To force the link and overwrite all conflicting files:
  brew link --overwrite node

To list all files that would be deleted:
  brew link --overwrite --dry-run node

Possible conflicting files are:
/usr/local/bin/node
/usr/local/share/man/man1/node.1
/usr/local/lib/dtrace/node.d
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
<U+1F37A>  /usr/local/Cellar/node/9.8.0: 5,125 files, 49.7MB
```

Looking for a solution, but I don't think we need to block release for this failure as its only a problem with test VM and not salt code.
