### ISSUE TITLE
[2017.7] [opensuse] [py2] integration.states.test_pkgrepo.PkgrepoTest.test_pkgrepo_03_with_comments

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt-jenkins#917]
```
Error Message

{} != {'comments': {'new': ['This is a comment', 'This is another comment'], 'old': [' [truncated]... - {} + {'comments': {'new': ['This is a comment', 'This is another comment'], +               'old': ['This is a comment']}}

Stacktrace

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 983, in decorator
    return func(cls, grains=cls.run_function('grains.items'))
  File "/tmp/kitchen/testing/tests/integration/states/test_pkgrepo.py", line 114, in test_pkgrepo_03_with_comments
    'This is another comment']
AssertionError: {} != {'comments': {'new': ['This is a comment', 'This is another comment'], 'old': [' [truncated]...
- {}
+ {'comments': {'new': ['This is a comment', 'This is another comment'],
+               'old': ['This is a comment']}}
		
```

**Comment by rallytime** [comment]
@garethgreenaway Can you take a look at this test failure when you get a moment?

**Comment by garethgreenaway** [comment]
Initially it appears that adding comments into zypper repos does nothing.
