### ISSUE TITLE
[2018.3][fedora 27][py2/py3] integration.modules.test_state_jinja_filters.StateModuleJinjaFiltersTest.test_path_which

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt-jenkins#920]
This should be fairly easy to fix.

```
Error Message

{u'ret': u'/bin/which'} != {u'ret': u'/usr/bin/which'} - {u'ret': u'/bin/which'} + {u'ret': u'/usr/bin/which'} ?            ++++ 

Stacktrace

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/jinja_filters.py", line 610, in test_path_which
    _expected)
AssertionError: {u'ret': u'/bin/which'} != {u'ret': u'/usr/bin/which'}
- {u'ret': u'/bin/which'}
+ {u'ret': u'/usr/bin/which'}
?            ++++

		
```

**Comment by gtmanfred** [comment]
Also for ssh

`integration.ssh.test_jinja_filters.SSHJinjaFiltersTest.test_path_which`

```
Error Message

{'ret': '/bin/which'} != {'ret': '/usr/bin/which'} - {'ret': '/bin/which'} + {'ret': '/usr/bin/which'} ?          ++++ 

Stacktrace

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/jinja_filters.py", line 610, in test_path_which
    _expected)
AssertionError: {'ret': '/bin/which'} != {'ret': '/usr/bin/which'}
- {'ret': '/bin/which'}
+ {'ret': '/usr/bin/which'}
?          ++++

		
```

**Comment by rallytime** [comment]
@garethgreenaway Can you grab this one?
