### ISSUE TITLE
[2017.7][opensuse][py2] Failures in boto

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt-jenkins#932]
```
    unit.utils.test_boto.BotoUtilsGetConnTestCase.test_conn_is_cache_with_profile
    unit.utils.test_boto.BotoUtilsGetConnTestCase.test_conn_is_cached
    unit.utils.test_boto.BotoUtilsGetConnTestCase.test_get_conn_error_raises_command_execution_error
    unit.utils.test_boto.BotoUtilsGetConnTestCase.test_get_conn_with_no_auth_params_raises_invocation_error
    unit.utils.test_boto.BotoUtilsGetConnTestCase.test_partial
```

**Comment by gtmanfred** [comment]
https://jenkinsci.saltstack.com/job/2017.7/view/All/job/salt-opensuse-py2/123/

**Comment by gtmanfred** [comment]
All of these are failing with 

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/moto/core/models.py", line 69, in wrapper
    self.start(reset=reset)
  File "/usr/lib/python2.7/site-packages/moto/core/models.py", line 56, in start
    self.enable_patching()
  File "/usr/lib/python2.7/site-packages/moto/core/models.py", line 186, in enable_patching
    botocore_mock.start()
  File "/usr/lib/python2.7/site-packages/responses.py", line 575, in start
    self._patcher.start()
  File "/usr/lib/python2.7/site-packages/mock.py", line 1396, in start
    result = self.__enter__()
  File "/usr/lib/python2.7/site-packages/mock.py", line 1252, in __enter__
    self.target = self.getter()
  File "/usr/lib/python2.7/site-packages/mock.py", line 1414, in <lambda>
    getter = lambda: _importer(target)
  File "/usr/lib/python2.7/site-packages/mock.py", line 1102, in _importer
    thing = _dot_lookup(thing, comp, import_path)
  File "/usr/lib/python2.7/site-packages/mock.py", line 1091, in _dot_lookup
    __import__(import_path)
ImportError: No module named vendored
		
```
