### ISSUE TITLE
[macosx] test_issue_7754 failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt-jenkins#936]
http://mac-jenkins:8080/job/2017.7/job/macOS-10.11-py3/46/#showFailuresLink

integration.shell.test_call.CallTest.test_issue_7754
integration.shell.test_runner.RunTest.test_issue_7754

```
Error Message

'Failed to setup the Syslog logging handler' not found in 'Process killed, unable to catch stderr output'
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/integration/shell/test_runner.py", line 120, in test_issue_7754
    self.assertIn("'doc.runner:'", ret[0])
AssertionError: "'doc.runner:'" not found in ['Process took more than 60 seconds to complete. Process Killed!']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/testing/tests/integration/shell/test_runner.py", line 129, in test_issue_7754
    '\n'.join(ret[1])
AssertionError: 'Failed to setup the Syslog logging handler' not found in 'Process killed, unable to catch stderr output'
```

**Comment by rallytime** [comment]
@Ch3LL Is this fixed now? Should this be closed?

**Comment by Ch3LL** [comment]
yesh
