### ISSUE TITLE
[tornado 5.0] tests unable to start

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt-jenkins#947]
```
20:17:46        20:17:46,736 [tests.support.parser                :67  ][ERROR   ] An un-handled exception was caught by salt-testing's global exception handler:
20:17:46        AttributeError: 'Future' object has no attribute 'exc_info'
20:17:46        Traceback (most recent call last):
20:17:46          File "/tmp/kitchen/testing/tests/runtests.py", line 789, in <module>
20:17:46            main()
20:17:46          File "/tmp/kitchen/testing/tests/runtests.py", line 774, in main
20:17:46            status = parser.run_integration_tests()
20:17:46          File "/tmp/kitchen/testing/tests/runtests.py", line 698, in run_integration_tests
20:17:46            with TestDaemon(self):
20:17:46          File "/tmp/kitchen/testing/tests/integration/__init__.py", line 239, in __enter__
20:17:46            grains = self.client.cmd('minion', 'grains.items')
20:17:46          File "/tmp/kitchen/testing/salt/client/__init__.py", line 758, in cmd
20:17:46            self.event.close_pub()
20:17:46          File "/tmp/kitchen/testing/salt/utils/event.py", line 391, in close_pub
20:17:46            self.subscriber.close()
20:17:46          File "/tmp/kitchen/testing/salt/transport/ipc.py", line 758, in close
20:17:46            self._read_stream_future.exc_info()
20:17:46        AttributeError: 'Future' object has no attribute 'exc_info'
20:17:46        20:17:46,737 [salt.log.setup                      :1158][ERROR   ] An un-handled exception was caught by salt's global exception handler:
20:17:46        AttributeError: 'Future' object has no attribute 'exc_info'
20:17:46        Traceback (most recent call last):
20:17:46          File "/tmp/kitchen/testing/tests/runtests.py", line 789, in <module>
20:17:46            main()
20:17:46          File "/tmp/kitchen/testing/tests/runtests.py", line 774, in main
20:17:46            status = parser.run_integration_tests()
20:17:46          File "/tmp/kitchen/testing/tests/runtests.py", line 698, in run_integration_tests
20:17:46            with TestDaemon(self):
20:17:46          File "/tmp/kitchen/testing/tests/integration/__init__.py", line 239, in __enter__
20:17:46            grains = self.client.cmd('minion', 'grains.items')
20:17:46          File "/tmp/kitchen/testing/salt/client/__init__.py", line 758, in cmd
20:17:46            self.event.close_pub()
20:17:46          File "/tmp/kitchen/testing/salt/utils/event.py", line 391, in close_pub
20:17:46            self.subscriber.close()
20:17:46          File "/tmp/kitchen/testing/salt/transport/ipc.py", line 758, in close
20:17:46            self._read_stream_future.exc_info()
20:17:46        AttributeError: 'Future' object has no attribute 'exc_info'
20:17:46        Traceback (most recent call last):
20:17:46          File "/tmp/kitchen/testing/tests/runtests.py", line 789, in <module>
20:17:46            main()
20:17:46          File "/tmp/kitchen/testing/tests/runtests.py", line 774, in main
20:17:46            status = parser.run_integration_tests()
20:17:46          File "/tmp/kitchen/testing/tests/runtests.py", line 698, in run_integration_tests
20:17:46            with TestDaemon(self):
20:17:46          File "/tmp/kitchen/testing/tests/integration/__init__.py", line 239, in __enter__
20:17:46            grains = self.client.cmd('minion', 'grains.items')
20:17:46          File "/tmp/kitchen/testing/salt/client/__init__.py", line 758, in cmd
20:17:46            self.event.close_pub()
20:17:46          File "/tmp/kitchen/testing/salt/utils/event.py", line 391, in close_pub
20:17:46            self.subscriber.close()
20:17:46          File "/tmp/kitchen/testing/salt/transport/ipc.py", line 758, in close
20:17:46            self._read_stream_future.exc_info()
20:17:46        AttributeError: 'Future' object has no attribute 'exc_info'
```

https://jenkinsci.saltstack.com/job/2017.7/job/salt-centos-7-py3-tornado5/2/console

**Comment by gtmanfred** [comment]
This has been fixed.
