### ISSUE TITLE
[2018.3] YAML serialization test failing on Arch

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#971]
The following test is failing on Arch:
- unit.serializers.test_serializers.TestSerializers.test_serialize_yaml

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/serializers/test_serializers.py", line 60, in test_serialize_yaml
    deserialized = yaml.deserialize(serialized)
  File "/tmp/kitchen/testing/salt/serializers/yaml.py", line 57, in deserialize
    raise DeserializationError(error)
DeserializationError: startswith first arg must be str, unicode, or tuple, not NoneType
```

https://jenkinsci.saltstack.com/job/2018.3/job/salt-arch-py2/lastCompletedBuild/testReport/

@terminalmage Can you take a look at this and fix it up?

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/47568
