### ISSUE TITLE
[2018.3.1] Several jobs not running - git clone from origin errors

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt-jenkins#977]
There are several jobs not running on the 2018.3.1 branch:

```
19:54:11 Fetching upstream changes from https://github.com/saltstack/salt/
19:54:11  > git --version # timeout=10
19:54:11  > git fetch --tags --progress https://github.com/saltstack/salt/ +refs/heads/*:refs/remotes/origin/* --depth=1
20:04:11 ERROR: Timeout after 10 minutes
20:04:11 ERROR: Error cloning remote repo 'origin'
20:04:11 hudson.plugins.git.GitException: Command "git fetch --tags --progress https://github.com/saltstack/salt/ +refs/heads/*:refs/remotes/origin/* --depth=1" returned status code 143:
20:04:11 stdout: 
20:04:11 stderr: remote: Counting objects: 45188, done.        
20:04:11 remote: Compressing objects:   0% (1/36303)           
<snipped>
Receiving objects:  71% (32472/45188), 90.88 MiB | 160.00 KiB/s   
20:04:12 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1996)
20:04:12 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1715)
20:04:12 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:72)
20:04:12 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:405)
20:04:12 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:614)
20:04:12 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
20:04:12 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
20:04:12 	at hudson.remoting.UserRequest.perform(UserRequest.java:210)
20:04:12 	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
20:04:12 	at hudson.remoting.Request$2.run(Request.java:364)
20:04:12 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
20:04:12 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
20:04:12 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
20:04:12 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
20:04:12 	at java.lang.Thread.run(Thread.java:748)
20:04:12 	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to kitchen-slave07-dev
20:04:12 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1737)
20:04:12 		at hudson.remoting.UserResponse.retrieve(UserRequest.java:313)
20:04:12 		at hudson.remoting.Channel.call(Channel.java:952)
20:04:12 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
20:04:12 		at sun.reflect.GeneratedMethodAccessor362.invoke(Unknown Source)
20:04:12 		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
20:04:12 		at java.lang.reflect.Method.invoke(Method.java:498)
20:04:12 		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
20:04:12 		at com.sun.proxy.$Proxy78.execute(Unknown Source)
20:04:12 		at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1120)
20:04:12 		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1160)
20:04:12 		at hudson.scm.SCM.checkout(SCM.java:504)
20:04:12 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1208)
20:04:12 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
20:04:12 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
20:04:12 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
20:04:12 		at hudson.model.Run.execute(Run.java:1727)
20:04:12 		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
20:04:12 		at hudson.model.ResourceController.execute(ResourceController.java:97)
20:04:12 		at hudson.model.Executor.run(Executor.java:429)
20:04:12 ERROR: Error cloning remote repo 'origin'
20:04:12 Performing Post build task...
```

@dubb-b Can you hard restart the kitchen nodes? @gtmanfred Said that this is what solved this problem in the past.

The latest jobs I saw this on was in the 2018.3.1 branch:
- arch py2
- cent7 py2/py3
- deb8 py2
- ubuntu 18 py2

There may be others, those are just the ones I checked this morning.

**Comment by dubb-b** [comment]
@rallytime these were restarted.

**Comment by rallytime** [comment]
Thanks!
